// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Llvm.NET.Interop
{
    public static partial class NativeMethods
    {
        /// <include file="Coroutines.xml" path='LibLLVMAPI/Function[@name="LLVMAddCoroEarlyPass"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMAddCoroEarlyPass( LLVMPassManagerRef PM );

        /// <include file="Coroutines.xml" path='LibLLVMAPI/Function[@name="LLVMAddCoroSplitPass"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMAddCoroSplitPass( LLVMPassManagerRef PM );

        /// <include file="Coroutines.xml" path='LibLLVMAPI/Function[@name="LLVMAddCoroElidePass"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMAddCoroElidePass( LLVMPassManagerRef PM );

        /// <include file="Coroutines.xml" path='LibLLVMAPI/Function[@name="LLVMAddCoroCleanupPass"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMAddCoroCleanupPass( LLVMPassManagerRef PM );

    }
}
