// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Llvm.NET.Interop
{
    /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/*[not(self::Item)]' />
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleArchType : global::System.Int32
    {
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_UnknownArch"]/*' />
        LibLLVMTripleArchType_UnknownArch = 0,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_arm"]/*' />
        LibLLVMTripleArchType_arm = 1,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_armeb"]/*' />
        LibLLVMTripleArchType_armeb = 2,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_aarch64"]/*' />
        LibLLVMTripleArchType_aarch64 = 3,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_aarch64_be"]/*' />
        LibLLVMTripleArchType_aarch64_be = 4,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_arc"]/*' />
        LibLLVMTripleArchType_arc = 5,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_avr"]/*' />
        LibLLVMTripleArchType_avr = 6,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_bpfel"]/*' />
        LibLLVMTripleArchType_bpfel = 7,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_bpfeb"]/*' />
        LibLLVMTripleArchType_bpfeb = 8,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_hexagon"]/*' />
        LibLLVMTripleArchType_hexagon = 9,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_mips"]/*' />
        LibLLVMTripleArchType_mips = 10,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_mipsel"]/*' />
        LibLLVMTripleArchType_mipsel = 11,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_mips64"]/*' />
        LibLLVMTripleArchType_mips64 = 12,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_mips64el"]/*' />
        LibLLVMTripleArchType_mips64el = 13,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_msp430"]/*' />
        LibLLVMTripleArchType_msp430 = 14,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_ppc"]/*' />
        LibLLVMTripleArchType_ppc = 15,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_ppc64"]/*' />
        LibLLVMTripleArchType_ppc64 = 16,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_ppc64le"]/*' />
        LibLLVMTripleArchType_ppc64le = 17,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_r600"]/*' />
        LibLLVMTripleArchType_r600 = 18,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_amdgcn"]/*' />
        LibLLVMTripleArchType_amdgcn = 19,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_riscv32"]/*' />
        LibLLVMTripleArchType_riscv32 = 20,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_riscv64"]/*' />
        LibLLVMTripleArchType_riscv64 = 21,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_sparc"]/*' />
        LibLLVMTripleArchType_sparc = 22,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_sparcv9"]/*' />
        LibLLVMTripleArchType_sparcv9 = 23,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_sparcel"]/*' />
        LibLLVMTripleArchType_sparcel = 24,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_systemz"]/*' />
        LibLLVMTripleArchType_systemz = 25,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_tce"]/*' />
        LibLLVMTripleArchType_tce = 26,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_tcele"]/*' />
        LibLLVMTripleArchType_tcele = 27,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_thumb"]/*' />
        LibLLVMTripleArchType_thumb = 28,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_thumbeb"]/*' />
        LibLLVMTripleArchType_thumbeb = 29,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_x86"]/*' />
        LibLLVMTripleArchType_x86 = 30,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_x86_64"]/*' />
        LibLLVMTripleArchType_x86_64 = 31,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_xcore"]/*' />
        LibLLVMTripleArchType_xcore = 32,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_nvptx"]/*' />
        LibLLVMTripleArchType_nvptx = 33,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_nvptx64"]/*' />
        LibLLVMTripleArchType_nvptx64 = 34,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_le32"]/*' />
        LibLLVMTripleArchType_le32 = 35,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_le64"]/*' />
        LibLLVMTripleArchType_le64 = 36,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_amdil"]/*' />
        LibLLVMTripleArchType_amdil = 37,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_amdil64"]/*' />
        LibLLVMTripleArchType_amdil64 = 38,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_hsail"]/*' />
        LibLLVMTripleArchType_hsail = 39,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_hsail64"]/*' />
        LibLLVMTripleArchType_hsail64 = 40,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_spir"]/*' />
        LibLLVMTripleArchType_spir = 41,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_spir64"]/*' />
        LibLLVMTripleArchType_spir64 = 42,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_kalimba"]/*' />
        LibLLVMTripleArchType_kalimba = 43,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_shave"]/*' />
        LibLLVMTripleArchType_shave = 44,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_lanai"]/*' />
        LibLLVMTripleArchType_lanai = 45,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_wasm32"]/*' />
        LibLLVMTripleArchType_wasm32 = 46,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_wasm64"]/*' />
        LibLLVMTripleArchType_wasm64 = 47,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_renderscript32"]/*' />
        LibLLVMTripleArchType_renderscript32 = 48,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_renderscript64"]/*' />
        LibLLVMTripleArchType_renderscript64 = 49,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleArchType"]/Item[@name="LibLLVMTripleArchType_LastArchType"]/*' />
        LibLLVMTripleArchType_LastArchType = 49,
    }

    /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/*[not(self::Item)]' />
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleSubArchType : global::System.Int32
    {
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_NoSubArch"]/*' />
        LibLLVMTripleSubArchType_NoSubArch = 0,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8_5a"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8_5a = 1,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8_4a"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8_4a = 2,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8_3a"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8_3a = 3,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8_2a"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8_2a = 4,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8_1a"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8_1a = 5,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8 = 6,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8r"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8r = 7,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8m_baseline"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8m_baseline = 8,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v8m_mainline"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v8m_mainline = 9,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v7"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v7 = 10,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v7em"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v7em = 11,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v7m"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v7m = 12,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v7s"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v7s = 13,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v7k"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v7k = 14,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v7ve"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v7ve = 15,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v6"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v6 = 16,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v6m"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v6m = 17,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v6k"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v6k = 18,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v6t2"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v6t2 = 19,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v5"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v5 = 20,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v5te"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v5te = 21,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_ARMSubArch_v4t"]/*' />
        LibLLVMTripleSubArchType_ARMSubArch_v4t = 22,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_KalimbaSubArch_v3"]/*' />
        LibLLVMTripleSubArchType_KalimbaSubArch_v3 = 23,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_KalimbaSubArch_v4"]/*' />
        LibLLVMTripleSubArchType_KalimbaSubArch_v4 = 24,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_KalimbaSubArch_v5"]/*' />
        LibLLVMTripleSubArchType_KalimbaSubArch_v5 = 25,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleSubArchType"]/Item[@name="LibLLVMTripleSubArchType_MipsSubArch_r6"]/*' />
        LibLLVMTripleSubArchType_MipsSubArch_r6 = 26,
    }

    /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/*[not(self::Item)]' />
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleVendorType : global::System.Int32
    {
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_UnknownVendor"]/*' />
        LibLLVMTripleVendorType_UnknownVendor = 0,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_Apple"]/*' />
        LibLLVMTripleVendorType_Apple = 1,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_PC"]/*' />
        LibLLVMTripleVendorType_PC = 2,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_SCEI"]/*' />
        LibLLVMTripleVendorType_SCEI = 3,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_BGP"]/*' />
        LibLLVMTripleVendorType_BGP = 4,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_BGQ"]/*' />
        LibLLVMTripleVendorType_BGQ = 5,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_Freescale"]/*' />
        LibLLVMTripleVendorType_Freescale = 6,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_IBM"]/*' />
        LibLLVMTripleVendorType_IBM = 7,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_ImaginationTechnologies"]/*' />
        LibLLVMTripleVendorType_ImaginationTechnologies = 8,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_MipsTechnologies"]/*' />
        LibLLVMTripleVendorType_MipsTechnologies = 9,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_NVIDIA"]/*' />
        LibLLVMTripleVendorType_NVIDIA = 10,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_CSR"]/*' />
        LibLLVMTripleVendorType_CSR = 11,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_Myriad"]/*' />
        LibLLVMTripleVendorType_Myriad = 12,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_AMD"]/*' />
        LibLLVMTripleVendorType_AMD = 13,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_Mesa"]/*' />
        LibLLVMTripleVendorType_Mesa = 14,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_SUSE"]/*' />
        LibLLVMTripleVendorType_SUSE = 15,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_OpenEmbedded"]/*' />
        LibLLVMTripleVendorType_OpenEmbedded = 16,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleVendorType"]/Item[@name="LibLLVMTripleVendorType_LastVendorType"]/*' />
        LibLLVMTripleVendorType_LastVendorType = 16,
    }

    /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/*[not(self::Item)]' />
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleOSType : global::System.Int32
    {
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_UnknownOS"]/*' />
        LibLLVMTripleOSType_UnknownOS = 0,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Ananas"]/*' />
        LibLLVMTripleOSType_Ananas = 1,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_CloudABI"]/*' />
        LibLLVMTripleOSType_CloudABI = 2,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Darwin"]/*' />
        LibLLVMTripleOSType_Darwin = 3,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_DragonFly"]/*' />
        LibLLVMTripleOSType_DragonFly = 4,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_FreeBSD"]/*' />
        LibLLVMTripleOSType_FreeBSD = 5,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Fuchsia"]/*' />
        LibLLVMTripleOSType_Fuchsia = 6,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_IOS"]/*' />
        LibLLVMTripleOSType_IOS = 7,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_KFreeBSD"]/*' />
        LibLLVMTripleOSType_KFreeBSD = 8,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Linux"]/*' />
        LibLLVMTripleOSType_Linux = 9,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Lv2"]/*' />
        LibLLVMTripleOSType_Lv2 = 10,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_MacOSX"]/*' />
        LibLLVMTripleOSType_MacOSX = 11,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_NetBSD"]/*' />
        LibLLVMTripleOSType_NetBSD = 12,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_OpenBSD"]/*' />
        LibLLVMTripleOSType_OpenBSD = 13,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Solaris"]/*' />
        LibLLVMTripleOSType_Solaris = 14,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Win32"]/*' />
        LibLLVMTripleOSType_Win32 = 15,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Haiku"]/*' />
        LibLLVMTripleOSType_Haiku = 16,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Minix"]/*' />
        LibLLVMTripleOSType_Minix = 17,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_RTEMS"]/*' />
        LibLLVMTripleOSType_RTEMS = 18,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_NaCl"]/*' />
        LibLLVMTripleOSType_NaCl = 19,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_CNK"]/*' />
        LibLLVMTripleOSType_CNK = 20,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_AIX"]/*' />
        LibLLVMTripleOSType_AIX = 21,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_CUDA"]/*' />
        LibLLVMTripleOSType_CUDA = 22,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_NVCL"]/*' />
        LibLLVMTripleOSType_NVCL = 23,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_AMDHSA"]/*' />
        LibLLVMTripleOSType_AMDHSA = 24,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_PS4"]/*' />
        LibLLVMTripleOSType_PS4 = 25,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_ELFIAMCU"]/*' />
        LibLLVMTripleOSType_ELFIAMCU = 26,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_TvOS"]/*' />
        LibLLVMTripleOSType_TvOS = 27,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_WatchOS"]/*' />
        LibLLVMTripleOSType_WatchOS = 28,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Mesa3D"]/*' />
        LibLLVMTripleOSType_Mesa3D = 29,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Contiki"]/*' />
        LibLLVMTripleOSType_Contiki = 30,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_AMDPAL"]/*' />
        LibLLVMTripleOSType_AMDPAL = 31,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_HermitCore"]/*' />
        LibLLVMTripleOSType_HermitCore = 32,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_Hurd"]/*' />
        LibLLVMTripleOSType_Hurd = 33,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_WASI"]/*' />
        LibLLVMTripleOSType_WASI = 34,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleOSType"]/Item[@name="LibLLVMTripleOSType_LastOSType"]/*' />
        LibLLVMTripleOSType_LastOSType = 34,
    }

    /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/*[not(self::Item)]' />
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleEnvironmentType : global::System.Int32
    {
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_UnknownEnvironment"]/*' />
        LibLLVMTripleEnvironmentType_UnknownEnvironment = 0,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_GNU"]/*' />
        LibLLVMTripleEnvironmentType_GNU = 1,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_GNUABIN32"]/*' />
        LibLLVMTripleEnvironmentType_GNUABIN32 = 2,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_GNUABI64"]/*' />
        LibLLVMTripleEnvironmentType_GNUABI64 = 3,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_GNUEABI"]/*' />
        LibLLVMTripleEnvironmentType_GNUEABI = 4,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_GNUEABIHF"]/*' />
        LibLLVMTripleEnvironmentType_GNUEABIHF = 5,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_GNUX32"]/*' />
        LibLLVMTripleEnvironmentType_GNUX32 = 6,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_CODE16"]/*' />
        LibLLVMTripleEnvironmentType_CODE16 = 7,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_EABI"]/*' />
        LibLLVMTripleEnvironmentType_EABI = 8,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_EABIHF"]/*' />
        LibLLVMTripleEnvironmentType_EABIHF = 9,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_Android"]/*' />
        LibLLVMTripleEnvironmentType_Android = 10,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_Musl"]/*' />
        LibLLVMTripleEnvironmentType_Musl = 11,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_MuslEABI"]/*' />
        LibLLVMTripleEnvironmentType_MuslEABI = 12,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_MuslEABIHF"]/*' />
        LibLLVMTripleEnvironmentType_MuslEABIHF = 13,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_MSVC"]/*' />
        LibLLVMTripleEnvironmentType_MSVC = 14,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_Itanium"]/*' />
        LibLLVMTripleEnvironmentType_Itanium = 15,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_Cygnus"]/*' />
        LibLLVMTripleEnvironmentType_Cygnus = 16,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_CoreCLR"]/*' />
        LibLLVMTripleEnvironmentType_CoreCLR = 17,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_Simulator"]/*' />
        LibLLVMTripleEnvironmentType_Simulator = 18,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleEnvironmentType"]/Item[@name="LibLLVMTripleEnvironmentType_LastEnvironmentType"]/*' />
        LibLLVMTripleEnvironmentType_LastEnvironmentType = 18,
    }

    /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleObjectFormatType"]/*[not(self::Item)]' />
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleObjectFormatType : global::System.Int32
    {
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleObjectFormatType"]/Item[@name="LibLLVMTripleObjectFormatType_UnknownObjectFormat"]/*' />
        LibLLVMTripleObjectFormatType_UnknownObjectFormat = 0,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleObjectFormatType"]/Item[@name="LibLLVMTripleObjectFormatType_COFF"]/*' />
        LibLLVMTripleObjectFormatType_COFF = 1,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleObjectFormatType"]/Item[@name="LibLLVMTripleObjectFormatType_ELF"]/*' />
        LibLLVMTripleObjectFormatType_ELF = 2,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleObjectFormatType"]/Item[@name="LibLLVMTripleObjectFormatType_MachO"]/*' />
        LibLLVMTripleObjectFormatType_MachO = 3,
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Enumeration[@name="LibLLVMTripleObjectFormatType"]/Item[@name="LibLLVMTripleObjectFormatType_Wasm"]/*' />
        LibLLVMTripleObjectFormatType_Wasm = 4,
    }

    public static partial class NativeMethods
    {
        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMParseTriple"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LibLLVMTripleRef LibLLVMParseTriple( [MarshalAs( UnmanagedType.LPStr )]string triple );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMGetHostTriple"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LibLLVMTripleRef LibLLVMGetHostTriple(  );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleOpEqual"]/*' />
        [return: MarshalAs( UnmanagedType.Bool )]
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern bool LibLLVMTripleOpEqual( LibLLVMTripleRef lhs, LibLLVMTripleRef rhs );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetArchType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleArchType LibLLVMTripleGetArchType( LibLLVMTripleRef triple );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetSubArchType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleSubArchType LibLLVMTripleGetSubArchType( LibLLVMTripleRef triple );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetVendorType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleVendorType LibLLVMTripleGetVendorType( LibLLVMTripleRef triple );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetOsType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleOSType LibLLVMTripleGetOsType( LibLLVMTripleRef triple );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleHasEnvironment"]/*' />
        [return: MarshalAs( UnmanagedType.Bool )]
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern bool LibLLVMTripleHasEnvironment( LibLLVMTripleRef triple );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetEnvironmentType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleEnvironmentType LibLLVMTripleGetEnvironmentType( LibLLVMTripleRef triple );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetEnvironmentVersion"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LibLLVMTripleGetEnvironmentVersion( LibLLVMTripleRef triple, out uint major, out uint minor, out uint micro );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetObjectFormatType"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleObjectFormatType LibLLVMTripleGetObjectFormatType( LibLLVMTripleRef triple );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleAsString"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleAsString( LibLLVMTripleRef triple, bool normalize );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetArchTypeName"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetArchTypeName( global::Llvm.NET.Interop.LibLLVMTripleArchType type );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetSubArchTypeName"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetSubArchTypeName( global::Llvm.NET.Interop.LibLLVMTripleSubArchType type );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetVendorTypeName"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetVendorTypeName( global::Llvm.NET.Interop.LibLLVMTripleVendorType vendor );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetOsTypeName"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetOsTypeName( global::Llvm.NET.Interop.LibLLVMTripleOSType osType );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetEnvironmentTypeName"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetEnvironmentTypeName( global::Llvm.NET.Interop.LibLLVMTripleEnvironmentType environmentType );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMTripleGetObjectFormatTypeName"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetObjectFormatTypeName( global::Llvm.NET.Interop.LibLLVMTripleObjectFormatType objectFormatType );

        /// <include file="TripleBindings.xml" path='LibLLVMAPI/Function[@name="LibLLVMNormalizeTriple"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMNormalizeTriple( [MarshalAs( UnmanagedType.LPStr )]string triple );

    }
}
