// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Llvm.NET.Interop
{
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleArchType : global::System.Int32
    {
        LibLLVMTripleArchType_UnknownArch = 0,
        LibLLVMTripleArchType_arm = 1,
        LibLLVMTripleArchType_armeb = 2,
        LibLLVMTripleArchType_aarch64 = 3,
        LibLLVMTripleArchType_aarch64_be = 4,
        LibLLVMTripleArchType_arc = 5,
        LibLLVMTripleArchType_avr = 6,
        LibLLVMTripleArchType_bpfel = 7,
        LibLLVMTripleArchType_bpfeb = 8,
        LibLLVMTripleArchType_hexagon = 9,
        LibLLVMTripleArchType_mips = 10,
        LibLLVMTripleArchType_mipsel = 11,
        LibLLVMTripleArchType_mips64 = 12,
        LibLLVMTripleArchType_mips64el = 13,
        LibLLVMTripleArchType_msp430 = 14,
        LibLLVMTripleArchType_ppc = 15,
        LibLLVMTripleArchType_ppc64 = 16,
        LibLLVMTripleArchType_ppc64le = 17,
        LibLLVMTripleArchType_r600 = 18,
        LibLLVMTripleArchType_amdgcn = 19,
        LibLLVMTripleArchType_riscv32 = 20,
        LibLLVMTripleArchType_riscv64 = 21,
        LibLLVMTripleArchType_sparc = 22,
        LibLLVMTripleArchType_sparcv9 = 23,
        LibLLVMTripleArchType_sparcel = 24,
        LibLLVMTripleArchType_systemz = 25,
        LibLLVMTripleArchType_tce = 26,
        LibLLVMTripleArchType_tcele = 27,
        LibLLVMTripleArchType_thumb = 28,
        LibLLVMTripleArchType_thumbeb = 29,
        LibLLVMTripleArchType_x86 = 30,
        LibLLVMTripleArchType_x86_64 = 31,
        LibLLVMTripleArchType_xcore = 32,
        LibLLVMTripleArchType_nvptx = 33,
        LibLLVMTripleArchType_nvptx64 = 34,
        LibLLVMTripleArchType_le32 = 35,
        LibLLVMTripleArchType_le64 = 36,
        LibLLVMTripleArchType_amdil = 37,
        LibLLVMTripleArchType_amdil64 = 38,
        LibLLVMTripleArchType_hsail = 39,
        LibLLVMTripleArchType_hsail64 = 40,
        LibLLVMTripleArchType_spir = 41,
        LibLLVMTripleArchType_spir64 = 42,
        LibLLVMTripleArchType_kalimba = 43,
        LibLLVMTripleArchType_shave = 44,
        LibLLVMTripleArchType_lanai = 45,
        LibLLVMTripleArchType_wasm32 = 46,
        LibLLVMTripleArchType_wasm64 = 47,
        LibLLVMTripleArchType_renderscript32 = 48,
        LibLLVMTripleArchType_renderscript64 = 49,
        LibLLVMTripleArchType_LastArchType = 49,
    }

    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleSubArchType : global::System.Int32
    {
        LibLLVMTripleSubArchType_NoSubArch = 0,
        LibLLVMTripleSubArchType_ARMSubArch_v8_5a = 1,
        LibLLVMTripleSubArchType_ARMSubArch_v8_4a = 2,
        LibLLVMTripleSubArchType_ARMSubArch_v8_3a = 3,
        LibLLVMTripleSubArchType_ARMSubArch_v8_2a = 4,
        LibLLVMTripleSubArchType_ARMSubArch_v8_1a = 5,
        LibLLVMTripleSubArchType_ARMSubArch_v8 = 6,
        LibLLVMTripleSubArchType_ARMSubArch_v8r = 7,
        LibLLVMTripleSubArchType_ARMSubArch_v8m_baseline = 8,
        LibLLVMTripleSubArchType_ARMSubArch_v8m_mainline = 9,
        LibLLVMTripleSubArchType_ARMSubArch_v7 = 10,
        LibLLVMTripleSubArchType_ARMSubArch_v7em = 11,
        LibLLVMTripleSubArchType_ARMSubArch_v7m = 12,
        LibLLVMTripleSubArchType_ARMSubArch_v7s = 13,
        LibLLVMTripleSubArchType_ARMSubArch_v7k = 14,
        LibLLVMTripleSubArchType_ARMSubArch_v7ve = 15,
        LibLLVMTripleSubArchType_ARMSubArch_v6 = 16,
        LibLLVMTripleSubArchType_ARMSubArch_v6m = 17,
        LibLLVMTripleSubArchType_ARMSubArch_v6k = 18,
        LibLLVMTripleSubArchType_ARMSubArch_v6t2 = 19,
        LibLLVMTripleSubArchType_ARMSubArch_v5 = 20,
        LibLLVMTripleSubArchType_ARMSubArch_v5te = 21,
        LibLLVMTripleSubArchType_ARMSubArch_v4t = 22,
        LibLLVMTripleSubArchType_KalimbaSubArch_v3 = 23,
        LibLLVMTripleSubArchType_KalimbaSubArch_v4 = 24,
        LibLLVMTripleSubArchType_KalimbaSubArch_v5 = 25,
        LibLLVMTripleSubArchType_MipsSubArch_r6 = 26,
    }

    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleVendorType : global::System.Int32
    {
        LibLLVMTripleVendorType_UnknownVendor = 0,
        LibLLVMTripleVendorType_Apple = 1,
        LibLLVMTripleVendorType_PC = 2,
        LibLLVMTripleVendorType_SCEI = 3,
        LibLLVMTripleVendorType_BGP = 4,
        LibLLVMTripleVendorType_BGQ = 5,
        LibLLVMTripleVendorType_Freescale = 6,
        LibLLVMTripleVendorType_IBM = 7,
        LibLLVMTripleVendorType_ImaginationTechnologies = 8,
        LibLLVMTripleVendorType_MipsTechnologies = 9,
        LibLLVMTripleVendorType_NVIDIA = 10,
        LibLLVMTripleVendorType_CSR = 11,
        LibLLVMTripleVendorType_Myriad = 12,
        LibLLVMTripleVendorType_AMD = 13,
        LibLLVMTripleVendorType_Mesa = 14,
        LibLLVMTripleVendorType_SUSE = 15,
        LibLLVMTripleVendorType_OpenEmbedded = 16,
        LibLLVMTripleVendorType_LastVendorType = 16,
    }

    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleOSType : global::System.Int32
    {
        LibLLVMTripleOSType_UnknownOS = 0,
        LibLLVMTripleOSType_Ananas = 1,
        LibLLVMTripleOSType_CloudABI = 2,
        LibLLVMTripleOSType_Darwin = 3,
        LibLLVMTripleOSType_DragonFly = 4,
        LibLLVMTripleOSType_FreeBSD = 5,
        LibLLVMTripleOSType_Fuchsia = 6,
        LibLLVMTripleOSType_IOS = 7,
        LibLLVMTripleOSType_KFreeBSD = 8,
        LibLLVMTripleOSType_Linux = 9,
        LibLLVMTripleOSType_Lv2 = 10,
        LibLLVMTripleOSType_MacOSX = 11,
        LibLLVMTripleOSType_NetBSD = 12,
        LibLLVMTripleOSType_OpenBSD = 13,
        LibLLVMTripleOSType_Solaris = 14,
        LibLLVMTripleOSType_Win32 = 15,
        LibLLVMTripleOSType_Haiku = 16,
        LibLLVMTripleOSType_Minix = 17,
        LibLLVMTripleOSType_RTEMS = 18,
        LibLLVMTripleOSType_NaCl = 19,
        LibLLVMTripleOSType_CNK = 20,
        LibLLVMTripleOSType_AIX = 21,
        LibLLVMTripleOSType_CUDA = 22,
        LibLLVMTripleOSType_NVCL = 23,
        LibLLVMTripleOSType_AMDHSA = 24,
        LibLLVMTripleOSType_PS4 = 25,
        LibLLVMTripleOSType_ELFIAMCU = 26,
        LibLLVMTripleOSType_TvOS = 27,
        LibLLVMTripleOSType_WatchOS = 28,
        LibLLVMTripleOSType_Mesa3D = 29,
        LibLLVMTripleOSType_Contiki = 30,
        LibLLVMTripleOSType_AMDPAL = 31,
        LibLLVMTripleOSType_HermitCore = 32,
        LibLLVMTripleOSType_Hurd = 33,
        LibLLVMTripleOSType_WASI = 34,
        LibLLVMTripleOSType_LastOSType = 34,
    }

    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleEnvironmentType : global::System.Int32
    {
        LibLLVMTripleEnvironmentType_UnknownEnvironment = 0,
        LibLLVMTripleEnvironmentType_GNU = 1,
        LibLLVMTripleEnvironmentType_GNUABIN32 = 2,
        LibLLVMTripleEnvironmentType_GNUABI64 = 3,
        LibLLVMTripleEnvironmentType_GNUEABI = 4,
        LibLLVMTripleEnvironmentType_GNUEABIHF = 5,
        LibLLVMTripleEnvironmentType_GNUX32 = 6,
        LibLLVMTripleEnvironmentType_CODE16 = 7,
        LibLLVMTripleEnvironmentType_EABI = 8,
        LibLLVMTripleEnvironmentType_EABIHF = 9,
        LibLLVMTripleEnvironmentType_Android = 10,
        LibLLVMTripleEnvironmentType_Musl = 11,
        LibLLVMTripleEnvironmentType_MuslEABI = 12,
        LibLLVMTripleEnvironmentType_MuslEABIHF = 13,
        LibLLVMTripleEnvironmentType_MSVC = 14,
        LibLLVMTripleEnvironmentType_Itanium = 15,
        LibLLVMTripleEnvironmentType_Cygnus = 16,
        LibLLVMTripleEnvironmentType_CoreCLR = 17,
        LibLLVMTripleEnvironmentType_Simulator = 18,
        LibLLVMTripleEnvironmentType_LastEnvironmentType = 18,
    }

    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LibLLVMTripleObjectFormatType : global::System.Int32
    {
        LibLLVMTripleObjectFormatType_UnknownObjectFormat = 0,
        LibLLVMTripleObjectFormatType_COFF = 1,
        LibLLVMTripleObjectFormatType_ELF = 2,
        LibLLVMTripleObjectFormatType_MachO = 3,
        LibLLVMTripleObjectFormatType_Wasm = 4,
    }

    public static partial class NativeMethods
    {
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LibLLVMTripleRef LibLLVMParseTriple( [MarshalAs( UnmanagedType.LPStr )]string triple );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LibLLVMTripleRef LibLLVMGetHostTriple(  );

        [return: MarshalAs( UnmanagedType.Bool )]
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern bool LibLLVMTripleOpEqual( LibLLVMTripleRef lhs, LibLLVMTripleRef rhs );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleArchType LibLLVMTripleGetArchType( LibLLVMTripleRef triple );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleSubArchType LibLLVMTripleGetSubArchType( LibLLVMTripleRef triple );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleVendorType LibLLVMTripleGetVendorType( LibLLVMTripleRef triple );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleOSType LibLLVMTripleGetOsType( LibLLVMTripleRef triple );

        [return: MarshalAs( UnmanagedType.Bool )]
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern bool LibLLVMTripleHasEnvironment( LibLLVMTripleRef triple );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleEnvironmentType LibLLVMTripleGetEnvironmentType( LibLLVMTripleRef triple );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LibLLVMTripleGetEnvironmentVersion( LibLLVMTripleRef triple, out uint major, out uint minor, out uint micro );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern global::Llvm.NET.Interop.LibLLVMTripleObjectFormatType LibLLVMTripleGetObjectFormatType( LibLLVMTripleRef triple );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleAsString( LibLLVMTripleRef triple, bool normalize );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetArchTypeName( global::Llvm.NET.Interop.LibLLVMTripleArchType type );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetSubArchTypeName( global::Llvm.NET.Interop.LibLLVMTripleSubArchType type );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetVendorTypeName( global::Llvm.NET.Interop.LibLLVMTripleVendorType vendor );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetOsTypeName( global::Llvm.NET.Interop.LibLLVMTripleOSType osType );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetEnvironmentTypeName( global::Llvm.NET.Interop.LibLLVMTripleEnvironmentType environmentType );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMTripleGetObjectFormatTypeName( global::Llvm.NET.Interop.LibLLVMTripleObjectFormatType objectFormatType );

        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( DisposeMessageMarshaler ) )]
        public static extern string LibLLVMNormalizeTriple( [MarshalAs( UnmanagedType.LPStr )]string triple );

    }
}
