### YamlMime:ManagedReference
items:
- uid: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
  commentId: T:Ubiquity.NET.Llvm.Values.UnnamedAddressKind
  id: UnnamedAddressKind
  parent: Ubiquity.NET.Llvm.Values
  children:
  - Ubiquity.NET.Llvm.Values.UnnamedAddressKind.Global
  - Ubiquity.NET.Llvm.Values.UnnamedAddressKind.Local
  - Ubiquity.NET.Llvm.Values.UnnamedAddressKind.None
  langs:
  - csharp
  - vb
  name: UnnamedAddressKind
  nameWithType: UnnamedAddressKind
  fullName: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
  type: Enum
  source:
    remote:
      path: src/Ubiquity.NET.Llvm/Values/GlobalValue.cs
      branch: LLVM20
      repo: https://github.com/smaillet/Llvm.NET.git
    id: UnnamedAddressKind
    path: ../src/Ubiquity.NET.Llvm/Values/GlobalValue.cs
    startLine: 95
  assemblies:
  - Ubiquity.NET.Llvm
  namespace: Ubiquity.NET.Llvm.Values
  summary: Unnamed address state of a global value
  example: []
  syntax:
    content: public enum UnnamedAddressKind
    content.vb: Public Enum UnnamedAddressKind
- uid: Ubiquity.NET.Llvm.Values.UnnamedAddressKind.None
  commentId: F:Ubiquity.NET.Llvm.Values.UnnamedAddressKind.None
  id: None
  parent: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
  langs:
  - csharp
  - vb
  name: None
  nameWithType: UnnamedAddressKind.None
  fullName: Ubiquity.NET.Llvm.Values.UnnamedAddressKind.None
  type: Field
  source:
    remote:
      path: src/Ubiquity.NET.Llvm/Values/GlobalValue.cs
      branch: LLVM20
      repo: https://github.com/smaillet/Llvm.NET.git
    id: None
    path: ../src/Ubiquity.NET.Llvm/Values/GlobalValue.cs
    startLine: 98
  assemblies:
  - Ubiquity.NET.Llvm
  namespace: Ubiquity.NET.Llvm.Values
  summary: Address of the global is significant
  example: []
  syntax:
    content: None = 0
    return:
      type: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
- uid: Ubiquity.NET.Llvm.Values.UnnamedAddressKind.Local
  commentId: F:Ubiquity.NET.Llvm.Values.UnnamedAddressKind.Local
  id: Local
  parent: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
  langs:
  - csharp
  - vb
  name: Local
  nameWithType: UnnamedAddressKind.Local
  fullName: Ubiquity.NET.Llvm.Values.UnnamedAddressKind.Local
  type: Field
  source:
    remote:
      path: src/Ubiquity.NET.Llvm/Values/GlobalValue.cs
      branch: LLVM20
      repo: https://github.com/smaillet/Llvm.NET.git
    id: Local
    path: ../src/Ubiquity.NET.Llvm/Values/GlobalValue.cs
    startLine: 101
  assemblies:
  - Ubiquity.NET.Llvm
  namespace: Ubiquity.NET.Llvm.Values
  summary: Address of the global is locally significant
  example: []
  syntax:
    content: Local = 1
    return:
      type: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
- uid: Ubiquity.NET.Llvm.Values.UnnamedAddressKind.Global
  commentId: F:Ubiquity.NET.Llvm.Values.UnnamedAddressKind.Global
  id: Global
  parent: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
  langs:
  - csharp
  - vb
  name: Global
  nameWithType: UnnamedAddressKind.Global
  fullName: Ubiquity.NET.Llvm.Values.UnnamedAddressKind.Global
  type: Field
  source:
    remote:
      path: src/Ubiquity.NET.Llvm/Values/GlobalValue.cs
      branch: LLVM20
      repo: https://github.com/smaillet/Llvm.NET.git
    id: Global
    path: ../src/Ubiquity.NET.Llvm/Values/GlobalValue.cs
    startLine: 104
  assemblies:
  - Ubiquity.NET.Llvm
  namespace: Ubiquity.NET.Llvm.Values
  summary: Address of the global is globally significant
  example: []
  syntax:
    content: Global = 2
    return:
      type: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
references:
- uid: Ubiquity.NET.Llvm.Values
  commentId: N:Ubiquity.NET.Llvm.Values
  href: Ubiquity.html
  name: Ubiquity.NET.Llvm.Values
  nameWithType: Ubiquity.NET.Llvm.Values
  fullName: Ubiquity.NET.Llvm.Values
  spec.csharp:
  - uid: Ubiquity
    name: Ubiquity
    href: Ubiquity.html
  - name: .
  - uid: Ubiquity.NET
    name: NET
    href: Ubiquity.NET.html
  - name: .
  - uid: Ubiquity.NET.Llvm
    name: Llvm
    href: Ubiquity.NET.Llvm.html
  - name: .
  - uid: Ubiquity.NET.Llvm.Values
    name: Values
    href: Ubiquity.NET.Llvm.Values.html
  spec.vb:
  - uid: Ubiquity
    name: Ubiquity
    href: Ubiquity.html
  - name: .
  - uid: Ubiquity.NET
    name: NET
    href: Ubiquity.NET.html
  - name: .
  - uid: Ubiquity.NET.Llvm
    name: Llvm
    href: Ubiquity.NET.Llvm.html
  - name: .
  - uid: Ubiquity.NET.Llvm.Values
    name: Values
    href: Ubiquity.NET.Llvm.Values.html
- uid: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
  commentId: T:Ubiquity.NET.Llvm.Values.UnnamedAddressKind
  parent: Ubiquity.NET.Llvm.Values
  href: Ubiquity.NET.Llvm.Values.UnnamedAddressKind.html
  name: UnnamedAddressKind
  nameWithType: UnnamedAddressKind
  fullName: Ubiquity.NET.Llvm.Values.UnnamedAddressKind
