version: 5.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

image: Visual Studio 2019

environment:
  docspush_email: 32618965+cibuild-telliam@users.noreply.github.com
  docspush_username: cibuild-telliam
  docspush_access_token:
    secure: QqWCIyFM6uBBbkW1jnlVGsMQWy+9aPY9rhD56oNT2L/0Cmw2bynROEsrUrOPpBrk
  IsAutomatedBuild: 'true'

skip_commits:
  files:
    - '**\*.md'

init:
  - git config --global core.safecrlf false
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: true

build_script:
  - ps: .\Build-All.ps1 -BuildMode All

deploy_script:
  - ps: .\Push-Docs.ps1

test_script:
  - ps: .\Invoke-UnitTests.ps1; Set-Culture fr-FR; .\Invoke-UnitTests.ps1;

artifacts:
  - path: .\BuildOutput\Nuget\*.nupkg
