// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LlvmBindingsGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal partial class ExternalDocXmlTemplate : ExternalDocXmlTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!--\r\n;; ========================================================================" +
                    "======\r\n;; <auto-generated>\r\n;;     This file was generated by a tool.\r\n;;     R" +
                    "untime Version: ");
            
            #line 10 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ToolVersion));
            
            #line default
            #line hidden
            this.Write(@"
;;
;;     Changes to this file may cause incorrect behavior and will be lost if
;;     the code is regenerated.
;; </auto-generated>
;; <usage>
;;     This file contains the bare bones skeleton doc comments info that the
;;     generated code files refer to. If the orginal source contained comments,
;;     those comments are generated here as the ""remarks"" element to aid in
;;     completing the docs. This always generated file is created with a .g.xml
;;     extension, however the generated C# code includes the form with the "".g""
;;     in the extension. This prevents the generation of this skeleton from
;;     overwriting any customized docs data. Any new entries need merging into
;;     the real version with all the manual edits.
;; </usage>
;; ==============================================================================
-->
<LibLlvmAPI>
");
            
            #line 28 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var e in Enums){
            
            #line default
            #line hidden
            this.Write("    <Enumeration name=\"");
            
            #line 29 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(e.Name));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <summary>TODO: Provide summary for ");
            
            #line 30 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(e.Name));
            
            #line default
            #line hidden
            this.Write(" Enumeration</summary>\r\n");
            
            #line 31 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
if( e.Comment.Any() ){
            
            #line default
            #line hidden
            this.Write("        <remarks>\r\n");
            
            #line 33 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var commentLine in e.Comment){
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 34 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commentLine));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 35 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        </remarks>\r\n");
            
            #line 37 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 38 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var enumItem in e.Members){
            
            #line default
            #line hidden
            this.Write("        <Item name=\"");
            
            #line 39 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumItem.Name));
            
            #line default
            #line hidden
            this.Write("\">\r\n            <summary>TODO: Provide summary for ");
            
            #line 40 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(e.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 40 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumItem.Name));
            
            #line default
            #line hidden
            this.Write(" Enumeration</summary>\r\n        </Item>\r\n");
            
            #line 42 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    </Enumeration>\r\n");
            
            #line 44 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 45 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var d in Delegates){
            
            #line default
            #line hidden
            this.Write("    <Delegate name=\"");
            
            #line 46 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(d.Name));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <summary>TODO: Provide summary for Delegate ");
            
            #line 47 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(d.Name));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n");
            
            #line 48 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var p in d.ParameterNames){
            
            #line default
            #line hidden
            this.Write("        <param name=\"");
            
            #line 49 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p));
            
            #line default
            #line hidden
            this.Write("\">TODO: Provide details of parameter ");
            
            #line 49 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p));
            
            #line default
            #line hidden
            this.Write("</param>\r\n");
            
            #line 50 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 50 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
if(d.HasNonVoidReturn){
            
            #line default
            #line hidden
            this.Write("        <returns>TODO: Document return value</returns>\r\n");
            
            #line 52 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    </Delegate>\r\n");
            
            #line 54 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 55 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var f in Functions){
            
            #line default
            #line hidden
            this.Write("    <Function name=\"");
            
            #line 56 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(f.Name));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <summary>TODO: Provide summary for Function ");
            
            #line 57 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(f.Name));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n");
            
            #line 58 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var p in f.ParameterNames){
            
            #line default
            #line hidden
            this.Write("        <param name=\"");
            
            #line 59 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p));
            
            #line default
            #line hidden
            this.Write("\">TODO: Provide details of parameter ");
            
            #line 59 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p));
            
            #line default
            #line hidden
            this.Write("</param>\r\n");
            
            #line 60 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 60 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
if(f.HasNonVoidReturn){
            
            #line default
            #line hidden
            this.Write("        <returns>TODO: Document return value</returns>\r\n");
            
            #line 62 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    </Function>\r\n");
            
            #line 64 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 65 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var s in ValueTypes){
            
            #line default
            #line hidden
            this.Write("    <Struct name=\"");
            
            #line 66 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.Name));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <summary>TODO: Provide summary for struct ");
            
            #line 67 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.Name));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n");
            
            #line 68 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
if( s.GetParsedComment().Any() ){
            
            #line default
            #line hidden
            this.Write("        <remarks>\r\n");
            
            #line 70 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var commentLine in s.GetParsedComment()){
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 71 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commentLine));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 72 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        </remarks>\r\n");
            
            #line 74 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 75 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
foreach(var fld in s.Fields){
            
            #line default
            #line hidden
            this.Write("        <Field name=\"");
            
            #line 76 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fld.Name));
            
            #line default
            #line hidden
            this.Write("\">\r\n            <summary>TODO: Provide summary for field ");
            
            #line 77 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 77 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fld.Name));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n        </Field>\r\n");
            
            #line 79 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    </Struct>\r\n");
            
            #line 81 "D:\GitHub\Ubiquity.NET\Llvm.Net\src\Interop\LlvmBindingsGenerator\Templates\T4\ExternalDocXmlTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("</LibLlvmAPI>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal class ExternalDocXmlTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
