// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 20.1.0-alpha.0.0.ci-ZZZ.601495633+d1254fe9f1777d1dc7521c608b84dde1ba5175e0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Ubiquity.NET.Llvm.Interop
{
    /// <summary>Global LLVM object handle</summary>
    [SuppressMessage( "Design", "CA1060:Move pinvokes to native methods class", Justification = "Called ONLY by this class" )]
    public partial class LLVMOperandBundleRef
        : LlvmObjectRef
    {
        /// <summary>Initializes an instance of <see cref="LLVMOperandBundleRef"/> with default values</summary>
        public LLVMOperandBundleRef()
            : base(ownsHandle: true)
        {
        }

        /// <summary>Initializes an instance of <see cref="LLVMOperandBundleRef"/></summary>
        /// <param name="handle">Raw native pointer for the handle</param>
        /// <param name="owner">Value to indicate whether the handle is owned or not</param>
        public LLVMOperandBundleRef( nint handle, bool owner )
            : base( owner )
        {
            SetHandle( handle );
        }

        /// <summary>Gets a Zero (<see langword="null"/>) value handle</summary>
        public static LLVMOperandBundleRef Zero { get; } = new LLVMOperandBundleRef(nint.Zero, false);

        /// <inheritdoc/>
        protected override bool ReleaseHandle( )
        {
            // critical safety check, base should never call ReleaseHandle on an invalid handle
            // but ABI usually can't handle that and would just crash the app, so make it
            // a NOP just in case.
            if( handle != nint.Zero )
            {
                LLVMDisposeOperandBundle( handle );
            }

            return true;
        }

        [LibraryImport( NativeMethods.LibraryPath )]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static unsafe partial void LLVMDisposeOperandBundle( nint p );
    }
}
