// -----------------------------------------------------------------------
// <copyright file="DwarfEnumerations.cs" company="Ubiquity.NET Contributors">
// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System;
using System.Diagnostics.CodeAnalysis;

using Ubiquity.NET.Llvm.Interop;

// The names describe what they are, further details are available in the DWARF specs
#pragma warning disable CS1591, SA1600, SA1602 // Enumeration items must be documented

// ReSharper disable IdentifierTypo
namespace Ubiquity.NET.Llvm.DebugInfo
{
    /// <summary>DWARF Debug information language</summary>
    public enum SourceLanguage
    {
        C89 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC89,
        C = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC,
        Ada83 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageAda83,
        CPlusPlus = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC_plus_plus,
        Cobol74 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageCobol74,
        Cobol85 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageCobol85,
        Fortran77 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageFortran77,
        Fortran90 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageFortran90,
        Pascal83 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguagePascal83,
        Modula2 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageModula2,
        Java = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageJava,
        C99 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC99,
        Ada95 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageAda95,
        Fortran95 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageFortran95,
        PLI = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguagePLI,
        ObjC = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageObjC,
        ObjCPlusPlus = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageObjC_plus_plus,
        UPC = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageUPC,
        D = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageD,
        Python = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguagePython,
        OpenCL = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageOpenCL,
        Go = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageGo,
        Modula3 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageModula3,
        Haskell = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageHaskell,
        CPlusPlus03 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC_plus_plus_03,
        CPlusPlus11 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC_plus_plus_11,
        OCaml = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageOCaml,
        Rust = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageRust,
        C11 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC11,
        Swift = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageSwift,
        Julia = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageJulia,
        Dylan = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageDylan,
        CPlusPlus14 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC_plus_plus_14,
        Fortran03 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageFortran03,
        Fortran08 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageFortran08,
        RenderScript = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageRenderScript,
        Bliss = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageBLISS,
        Kotlin = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageKotlin,
        Zig = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageZig,
        Crystal = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageCrystal,
        Cpp17 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC_plus_plus_17,
        Cpp20 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC_plus_plus_20,
        C17 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC17,
        Fortran18 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageFortran18,
        Ada2005 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageAda2005,
        Ada2012 = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageAda2012,
        HIP = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageHIP,
        Assembly = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageAssembly,
        CSharp = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageC_sharp,
        Mojo = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageMojo,
        GLSL = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageGLSL,
        GLSL_ES = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageGLSL_ES,
        HLSL = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageHLSL,
        OpenClCPP = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageOpenCL_CPP,
        CppForOpenCL = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageCPP_for_OpenCL,
        SYCL = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageSYCL,
        Ruby = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageRuby,
        Move = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageMove,
        HyLo = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageHylo,
        Metal = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageMetal,
        MipsAssembler = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageMips_Assembler,
        GoogleRenderScript = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageGOOGLE_RenderScript,
        BorlandDelphi = LLVMDWARFSourceLanguage.LLVMDWARFSourceLanguageBORLAND_Delphi,

#if LLVM_DWARF_SUPPORTS_USER_DEFINE_LANGUAGE
        /// <summary>Base value for unofficial languages ids</summary>
        UserMin = 0x8000,

        /// <summary>[Ubiquity.NET.Llvm] .NET IL Assembly language (ILAsm)</summary>
        ILAsm = UserMin + 0x01000,

        /// <summary>Max Value for unofficial language ids</summary>
        UserMax = 0xffff
#endif
    }

    // <summary>Tag kind for the debug information discriminated union nodes</summary>
    [SuppressMessage( "Microsoft.Design", "CA1028:EnumStorageShouldBeInt32", Justification = "matches interop type from native code" )]
    public enum Tag : ushort
    {
        None = 0, // No default/zero value defined by LLVM itself
        ArrayType = LibLLVMDwarfTag.DW_TAG_array_type,
        ClassType = LibLLVMDwarfTag.DW_TAG_class_type,
        EntryPoint = LibLLVMDwarfTag.DW_TAG_entry_point,
        EnumerationType = LibLLVMDwarfTag.DW_TAG_enumeration_type,
        FormalParameter = LibLLVMDwarfTag.DW_TAG_formal_parameter,
        ImportedDeclaration = LibLLVMDwarfTag.DW_TAG_imported_declaration,
        TagLabel = LibLLVMDwarfTag.DW_TAG_label,
        LexicalBlock = LibLLVMDwarfTag.DW_TAG_lexical_block,
        Member = LibLLVMDwarfTag.DW_TAG_member,
        PointerType = LibLLVMDwarfTag.DW_TAG_pointer_type,
        ReferenceType = LibLLVMDwarfTag.DW_TAG_reference_type,
        CompileUnit = LibLLVMDwarfTag.DW_TAG_compile_unit,
        StringType = LibLLVMDwarfTag.DW_TAG_string_type,
        StructureType = LibLLVMDwarfTag.DW_TAG_structure_type,
        SubroutineType = LibLLVMDwarfTag.DW_TAG_subroutine_type,
        TypeDef = LibLLVMDwarfTag.DW_TAG_typedef,
        UnionType = LibLLVMDwarfTag.DW_TAG_union_type,
        UnspecifiedParameters = LibLLVMDwarfTag.DW_TAG_unspecified_parameters,
        Variant = LibLLVMDwarfTag.DW_TAG_variant,
        CommonBlock = LibLLVMDwarfTag.DW_TAG_common_block,
        CommonInclusion = LibLLVMDwarfTag.DW_TAG_common_inclusion,
        Inheritance = LibLLVMDwarfTag.DW_TAG_inheritance,
        InlinedSubroutine = LibLLVMDwarfTag.DW_TAG_inlined_subroutine,
        Module = LibLLVMDwarfTag.DW_TAG_module,
        PointerToMemberType = LibLLVMDwarfTag.DW_TAG_ptr_to_member_type,
        SetType = LibLLVMDwarfTag.DW_TAG_set_type,
        SubrangeType = LibLLVMDwarfTag.DW_TAG_subrange_type,
        WithStatement = LibLLVMDwarfTag.DW_TAG_with_stmt,
        AccessDeclaration = LibLLVMDwarfTag.DW_TAG_access_declaration,
        BaseType = LibLLVMDwarfTag.DW_TAG_base_type,
        CatchBlock = LibLLVMDwarfTag.DW_TAG_catch_block,
        ConstType = LibLLVMDwarfTag.DW_TAG_const_type,
        Constant = LibLLVMDwarfTag.DW_TAG_constant,
        Enumerator = LibLLVMDwarfTag.DW_TAG_enumerator,
        FileType = LibLLVMDwarfTag.DW_TAG_file_type,
        Friend = LibLLVMDwarfTag.DW_TAG_friend,
        NameList = LibLLVMDwarfTag.DW_TAG_namelist,
        NameListItem = LibLLVMDwarfTag.DW_TAG_namelist_item,
        PackedType = LibLLVMDwarfTag.DW_TAG_packed_type,
        SubProgram = LibLLVMDwarfTag.DW_TAG_subprogram,
        TemplateTypeParameter = LibLLVMDwarfTag.DW_TAG_template_type_parameter,
        TemplateValueParameter = LibLLVMDwarfTag.DW_TAG_template_value_parameter,
        ThrownType = LibLLVMDwarfTag.DW_TAG_thrown_type,
        TryBlock = LibLLVMDwarfTag.DW_TAG_try_block,
        VariantPart = LibLLVMDwarfTag.DW_TAG_variant_part,
        Variable = LibLLVMDwarfTag.DW_TAG_variable,
        VolatileType = LibLLVMDwarfTag.DW_TAG_volatile_type,
        DwarfProcedure = LibLLVMDwarfTag.DW_TAG_dwarf_procedure,
        RestrictType = LibLLVMDwarfTag.DW_TAG_restrict_type,
        InterfaceType = LibLLVMDwarfTag.DW_TAG_interface_type,
        Namespace = LibLLVMDwarfTag.DW_TAG_namespace,
        ImportedModule = LibLLVMDwarfTag.DW_TAG_imported_module,
        UnspecifiedType = LibLLVMDwarfTag.DW_TAG_unspecified_type,
        PartialUnit = LibLLVMDwarfTag.DW_TAG_partial_unit,
        ImportedUnit = LibLLVMDwarfTag.DW_TAG_imported_unit,
        Condition = LibLLVMDwarfTag.DW_TAG_condition,
        SharedType = LibLLVMDwarfTag.DW_TAG_shared_type,
        TypeUnit = LibLLVMDwarfTag.DW_TAG_type_unit,
        RValueReferenceType = LibLLVMDwarfTag.DW_TAG_rvalue_reference_type,
        TemplateAlias = LibLLVMDwarfTag.DW_TAG_template_alias,
        CoArrayType = LibLLVMDwarfTag.DW_TAG_coarray_type,
        GenericSubrange = LibLLVMDwarfTag.DW_TAG_generic_subrange,
        DynamicType = LibLLVMDwarfTag.DW_TAG_dynamic_type,
        AtomicType = LibLLVMDwarfTag.DW_TAG_atomic_type,
        CallSite = LibLLVMDwarfTag.DW_TAG_call_site,
        CallSiteParameter = LibLLVMDwarfTag.DW_TAG_call_site_parameter,
        SkeletonUnit = LibLLVMDwarfTag.DW_TAG_skeleton_unit,
        ImmutableType = LibLLVMDwarfTag.DW_TAG_immutable_type,
        MIPSLoop = LibLLVMDwarfTag.DW_TAG_MIPS_loop,
        FormatLabel = LibLLVMDwarfTag.DW_TAG_format_label,
        FunctionTemplate = LibLLVMDwarfTag.DW_TAG_function_template,
        ClassTemplate = LibLLVMDwarfTag.DW_TAG_class_template,
        GNUTemplateParameter = LibLLVMDwarfTag.DW_TAG_GNU_template_template_param,
        GNUTemplateParameterPack = LibLLVMDwarfTag.DW_TAG_GNU_template_parameter_pack,
        GNUFormalParameterPack = LibLLVMDwarfTag.DW_TAG_GNU_formal_parameter_pack,
        GNUCallSite = LibLLVMDwarfTag.DW_TAG_GNU_call_site,
        GNUCallSiteParameter = LibLLVMDwarfTag.DW_TAG_GNU_call_site_parameter,
        AppleProperty = LibLLVMDwarfTag.DW_TAG_APPLE_property,
        BorlandProperty = LibLLVMDwarfTag.DW_TAG_BORLAND_property,
        BorlandDelphiString = LibLLVMDwarfTag.DW_TAG_BORLAND_Delphi_string,
        BorlandDelphiDynamicString = LibLLVMDwarfTag.DW_TAG_BORLAND_Delphi_dynamic_array,
        BorlandDelphiSet = LibLLVMDwarfTag.DW_TAG_BORLAND_Delphi_set,
        BorlandDelphiVariant = LibLLVMDwarfTag.DW_TAG_BORLAND_Delphi_variant,
    }

    /// <summary>Tags for qualified types</summary>
    public enum QualifiedTypeTag
    {
        None = 0,
        Const = Tag.ConstType,
        Volatile = Tag.VolatileType
    }

    /// <summary>Primitive type supported by the debug information</summary>
    public enum DiTypeKind
    {
        Invalid = 0,
        Address = LibLLVMDwarfAttributeEncoding.DW_ATE_address,
        Boolean = LibLLVMDwarfAttributeEncoding.DW_ATE_boolean,
        ComplexFloat = LibLLVMDwarfAttributeEncoding.DW_ATE_complex_float,
        Float = LibLLVMDwarfAttributeEncoding.DW_ATE_float,
        Signed = LibLLVMDwarfAttributeEncoding.DW_ATE_signed,
        SignedChar = LibLLVMDwarfAttributeEncoding.DW_ATE_signed_char,
        Unsigned = LibLLVMDwarfAttributeEncoding.DW_ATE_unsigned,
        UnsignedChar = LibLLVMDwarfAttributeEncoding.DW_ATE_unsigned_char,
        ImaginaryFloat = LibLLVMDwarfAttributeEncoding.DW_ATE_imaginary_float,
        PackedDecimal = LibLLVMDwarfAttributeEncoding.DW_ATE_packed_decimal,
        NumericString = LibLLVMDwarfAttributeEncoding.DW_ATE_numeric_string,
        Edited = LibLLVMDwarfAttributeEncoding.DW_ATE_edited,
        SignedFixed = LibLLVMDwarfAttributeEncoding.DW_ATE_signed_fixed,
        UnsignedFixed = LibLLVMDwarfAttributeEncoding.DW_ATE_unsigned_fixed,
        DecimalFloat = LibLLVMDwarfAttributeEncoding.DW_ATE_decimal_float,
        UTF = LibLLVMDwarfAttributeEncoding.DW_ATE_UTF,
        UCS = LibLLVMDwarfAttributeEncoding.DW_ATE_UCS,
        ASCII = LibLLVMDwarfAttributeEncoding.DW_ATE_ASCII,
        LoUser = LibLLVMDwarfAttributeEncoding.DW_ATE_lo_user,
        HiUser = LibLLVMDwarfAttributeEncoding.DW_ATE_hi_user
    }

    /// <summary>Debug information flags</summary>
    /// <remarks>
    /// The three accessibility flags are mutually exclusive and rolled together
    /// in the first two bits.
    /// </remarks>
    [Flags]
    [SuppressMessage( "Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "Matches the underlying wrapped API" )]
    [SuppressMessage( "Naming", "CA1700:Do not name enum values 'Reserved'", Justification = "Matches the underlying wrapped API" )]
    public enum DebugInfoFlags
    {
        None = LLVMDIFlags.LLVMDIFlagZero,
        Private = LLVMDIFlags.LLVMDIFlagPrivate,
        Protected = LLVMDIFlags.LLVMDIFlagProtected,
        Public = LLVMDIFlags.LLVMDIFlagPublic,
        ForwardDeclaration = LLVMDIFlags.LLVMDIFlagFwdDecl,
        AppleBlock = LLVMDIFlags.LLVMDIFlagAppleBlock,
        Virtual = LLVMDIFlags.LLVMDIFlagVirtual,
        Artificial = LLVMDIFlags.LLVMDIFlagArtificial,
        Explicit = LLVMDIFlags.LLVMDIFlagExplicit,
        Prototyped = LLVMDIFlags.LLVMDIFlagPrototyped,
        ObjcClassComplete = LLVMDIFlags.LLVMDIFlagObjcClassComplete,
        ObjectPointer = LLVMDIFlags.LLVMDIFlagObjectPointer,
        Vector = LLVMDIFlags.LLVMDIFlagVector,
        StaticMember = LLVMDIFlags.LLVMDIFlagStaticMember,
        LValueReference = LLVMDIFlags.LLVMDIFlagLValueReference,
        RValueReference = LLVMDIFlags.LLVMDIFlagRValueReference,
        Reserved = LLVMDIFlags.LLVMDIFlagReserved,
        SingleInheritance = LLVMDIFlags.LLVMDIFlagSingleInheritance,
        MultipleInheritance = LLVMDIFlags.LLVMDIFlagMultipleInheritance,
        VirtualInheritance = LLVMDIFlags.LLVMDIFlagVirtualInheritance,
        IntroducedVirtual = LLVMDIFlags.LLVMDIFlagIntroducedVirtual,
        BitField = LLVMDIFlags.LLVMDIFlagBitField,
        NoReturn = LLVMDIFlags.LLVMDIFlagNoReturn,
        TypePassByValue = LLVMDIFlags.LLVMDIFlagTypePassByValue,
        TypePassByReference = LLVMDIFlags.LLVMDIFlagTypePassByReference,
        EnumClass = LLVMDIFlags.LLVMDIFlagEnumClass,
        FixedEnum = LLVMDIFlags.LLVMDIFlagFixedEnum,
        Thunk = LLVMDIFlags.LLVMDIFlagThunk,
        NonTrivial = LLVMDIFlags.LLVMDIFlagNonTrivial,
        BigEndian = LLVMDIFlags.LLVMDIFlagBigEndian,
        LittleEndian = LLVMDIFlags.LLVMDIFlagLittleEndian,
        IndirectVirtualBase = LLVMDIFlags.LLVMDIFlagIndirectVirtualBase,
        AccessibilityMask = LLVMDIFlags.LLVMDIFlagAccessibility,
        PtrToMemberRep = LLVMDIFlags.LLVMDIFlagPtrToMemberRep
    }

    /// <summary>Debug information expression operator</summary>
    [SuppressMessage( "Microsoft.Design", "CA1028:EnumStorageShouldBeInt32", Justification = "Matches underlying interop type" )]
    public enum ExpressionOp
        : UInt64
    {
        Invalid = 0,
        Addr = 0x03,
        Deref = 0x06,
        Const1u = 0x08,
        Const1s = 0x09,
        Const2u = 0x0a,
        Const2s = 0x0b,
        Const4u = 0x0c,
        Const4s = 0x0d,
        Const8u = 0x0e,
        Const8s = 0x0f,
        Constu = 0x10,
        Consts = 0x11,
        Dup = 0x12,
        Drop = 0x13,
        Over = 0x14,
        Pick = 0x15,
        Swap = 0x16,
        Rot = 0x17,
        Xderef = 0x18,
        Abs = 0x19,
        And = 0x1a,
        Div = 0x1b,
        Minus = 0x1c,
        Mod = 0x1d,
        Mul = 0x1e,
        Neg = 0x1f,
        Not = 0x20,
        Or = 0x21,
        Plus = 0x22,
        PlusUconst = 0x23,
        Shl = 0x24,
        Shr = 0x25,
        Shra = 0x26,
        Xor = 0x27,
        Skip = 0x2f,
        Bra = 0x28,
        Eq = 0x29,
        Ge = 0x2a,
        Gt = 0x2b,
        Le = 0x2c,
        Lt = 0x2d,
        Ne = 0x2e,
        Lit0 = 0x30,
        Lit1 = 0x31,
        Lit2 = 0x32,
        Lit3 = 0x33,
        Lit4 = 0x34,
        Lit5 = 0x35,
        Lit6 = 0x36,
        Lit7 = 0x37,
        Lit8 = 0x38,
        Lit9 = 0x39,
        Lit10 = 0x3a,
        Lit11 = 0x3b,
        Lit12 = 0x3c,
        Lit13 = 0x3d,
        Lit14 = 0x3e,
        Lit15 = 0x3f,
        Lit16 = 0x40,
        Lit17 = 0x41,
        Lit18 = 0x42,
        Lit19 = 0x43,
        Lit20 = 0x44,
        Lit21 = 0x45,
        Lit22 = 0x46,
        Lit23 = 0x47,
        Lit24 = 0x48,
        Lit25 = 0x49,
        Lit26 = 0x4a,
        Lit27 = 0x4b,
        Lit28 = 0x4c,
        Lit29 = 0x4d,
        Lit30 = 0x4e,
        Lit31 = 0x4f,
        Reg0 = 0x50,
        Reg1 = 0x51,
        Reg2 = 0x52,
        Reg3 = 0x53,
        Reg4 = 0x54,
        Reg5 = 0x55,
        Reg6 = 0x56,
        Reg7 = 0x57,
        Reg8 = 0x58,
        Reg9 = 0x59,
        Reg10 = 0x5a,
        Reg11 = 0x5b,
        Reg12 = 0x5c,
        Reg13 = 0x5d,
        Reg14 = 0x5e,
        Reg15 = 0x5f,
        Reg16 = 0x60,
        Reg17 = 0x61,
        Reg18 = 0x62,
        Reg19 = 0x63,
        Reg20 = 0x64,
        Reg21 = 0x65,
        Reg22 = 0x66,
        Reg23 = 0x67,
        Reg24 = 0x68,
        Reg25 = 0x69,
        Reg26 = 0x6a,
        Reg27 = 0x6b,
        Reg28 = 0x6c,
        Reg29 = 0x6d,
        Reg30 = 0x6e,
        Reg31 = 0x6f,
        Breg0 = 0x70,
        Breg1 = 0x71,
        Breg2 = 0x72,
        Breg3 = 0x73,
        Breg4 = 0x74,
        Breg5 = 0x75,
        Breg6 = 0x76,
        Breg7 = 0x77,
        Breg8 = 0x78,
        Breg9 = 0x79,
        Breg10 = 0x7a,
        Breg11 = 0x7b,
        Breg12 = 0x7c,
        Breg13 = 0x7d,
        Breg14 = 0x7e,
        Breg15 = 0x7f,
        Breg16 = 0x80,
        Breg17 = 0x81,
        Breg18 = 0x82,
        Breg19 = 0x83,
        Breg20 = 0x84,
        Breg21 = 0x85,
        Breg22 = 0x86,
        Breg23 = 0x87,
        Breg24 = 0x88,
        Breg25 = 0x89,
        Breg26 = 0x8a,
        Breg27 = 0x8b,
        Breg28 = 0x8c,
        Breg29 = 0x8d,
        Breg30 = 0x8e,
        Breg31 = 0x8f,
        Regx = 0x90,
        Fbreg = 0x91,
        Bregx = 0x92,
        Piece = 0x93,
        DerefSize = 0x94,
        XderefSize = 0x95,
        Nop = 0x96,
        PushObjectAddress = 0x97,
        Call2 = 0x98,
        Call4 = 0x99,
        CallRef = 0x9a,
        FormTlsAddress = 0x9b,
        CallFrameCFA = 0x9c,
        BitPiece = 0x9d,
        ImplicitValue = 0x9e,
        StackValue = 0x9f,

        // Extensions for GNU-style thread-local storage.
        GnuPushTlsAddress = 0xe0,

        // Extensions for Fission proposal.
        GnuAddrIndex = 0xfb,
        GnuConstIndex = 0xfc
    }
}
