// <auto-generated/>
#nullable enable

// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// Licensed under the Apache-2.0 WITH LLVM-exception license. See the LICENSE.md file in the project root for full license information.

// .NET 7 added the various exception static methods for parameter validation
// This will back fill them for earlier versions.
//
// NOTE: C #14 extension keyword support is required to make this work.

#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace System
{
    file enum ResourceId
    {
        None = 0,
        Argument_EmptyOrWhiteSpaceString,
        ArgumentOutOfRange_Generic_MustBeEqual,
        ArgumentOutOfRange_Generic_MustBeGreater,
        ArgumentOutOfRange_Generic_MustBeGreaterOrEqual,
        ArgumentOutOfRange_Generic_MustBeLess,
        ArgumentOutOfRange_Generic_MustBeLessOrEqual,
        ArgumentOutOfRange_Generic_MustBeNonNegative,
        ArgumentOutOfRange_Generic_MustBeNonNegativeNonZero,
        ArgumentOutOfRange_Generic_MustBeNonZero,
        ArgumentOutOfRange_Generic_MustBeNotEqual
    }

    // Sadly, these are NOT localized messages as the official forms are.
    // There is no way, at least no-known way (easy or not) to inject resources
    // that would participate in loclization. (If the consumer even does that...)
    // The actual strings used are the same as the values in the official runtime
    // support so are at least compatible for "en-us". This fakes it to make it
    // more readable AND make it easier to shift if a means of injecting resources
    // is found.
    file static class ResourceIdExtensions
    {
        internal static string GetResourceString(this ResourceId id)
        {
            return id switch
            {
                ResourceId.Argument_EmptyOrWhiteSpaceString => "The value cannot be an empty string or composed entirely of whitespace.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeEqual => "{0} ('{1}') must be equal to '{2}'.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeGreater => "{0} ('{1}') must be greater than '{2}'.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeGreaterOrEqual => "{0} ('{1}') must be greater than or equal to '{2}'.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeLess => "{0} ('{1}') must be less than '{2}'.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeLessOrEqual => "{0} ('{1}') must be less than or equal to '{2}'.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeNonNegative => "{0} ('{1}') must be a non-negative value.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeNonNegativeNonZero => "{0} ('{1}') must be a non-negative and non-zero value.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeNonZero => "{0} ('{1}') must be a non-zero value.",
                ResourceId.ArgumentOutOfRange_Generic_MustBeNotEqual => "{0} ('{1}') must not be equal to '{2}'.",

                _ => throw new global::System.ComponentModel.InvalidEnumArgumentException(nameof(id), (int)id, typeof(ResourceId))
            };
        }
    }

    /// <summary>poly fill extensions for static methods added in .NET 7</summary>
    /// <remarks>
    /// This requires support of the C#14 keyword `extension` to work properly. There is
    /// no other way to add static methods to non-partial types for source compatibility.
    /// Otherwise code cannot use the modern .NET runtime implementations and instead
    /// must always use some extension methods, or litter around a LOT of #if/#else/#endif
    /// based on the framework version...
    /// </remarks>
    internal static class PolyFillExceptionValidators
    {
        /// <summary>Poly fill Extensions for <see cref="ArgumentException"/></summary>
        extension( global::System.ArgumentException )
        {
            /// <summary>Throw an <see cref="ArgumentException"/> if a string is <see langword="null"/>m empty, or all whitepsace.</summary>
            /// <param name="argument">input string to test</param>
            /// <param name="paramName">expression or name of the string to test; normally provided by compiler</param>
            /// <exception cref="ArgumentException">string is <see langword="null"/>m empty, or all whitepsace</exception>
            public static void ThrowIfNullOrWhiteSpace(
                [global::System.Diagnostics.CodeAnalysis.NotNullAttribute] string? argument,
                [global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute( nameof( argument ) )] string? paramName = null
                )
            {
                global::System.ArgumentNullException.ThrowIfNull( argument, paramName );

                // argument is non-null verified by this, sadly older frameworks don't have
                // attributes to declare that.
                if(string.IsNullOrWhiteSpace( argument ))
                {
                    throw new global::System.ArgumentException( "The value cannot be an empty string or composed entirely of whitespace.", paramName );
                }
            }
        }

        /// <summary>Poly fill Extensions for <see cref="ArgumentNullException"/></summary>
        extension( global::System.ArgumentNullException )
        {
            /// <summary>Throws an aexception if the tested argument is <see langword="null"/></summary>
            /// <param name="argument">value to test</param>
            /// <param name="paramName">expression for the name of the value; normally provided by compiler</param>
            /// <exception cref="ArgumentNullException"><paramref name="argument"/> is <see langword="null"/></exception>
            public static void ThrowIfNull(
                [global::System.Diagnostics.CodeAnalysis.NotNullAttribute] object? argument,
                [global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute( nameof( argument ) )] string? paramName = default
                )
            {
                if(argument is null)
                {
                    throw new global::System.ArgumentNullException( paramName );
                }
            }
        }

        /// <summary>Poly fill Extensions for <see cref="ObjectDisposedException"/></summary>
        extension( global::System.ObjectDisposedException )
        {
            /// <summary>Throws an <see cref="ObjectDisposedException"/> if <paramref name="condition"/> is <see langword="true"/>.</summary>
            /// <param name="condition">Condition to determine if the instance is disposed</param>
            /// <param name="instance">instance that is tested; Used to get type name for exception</param>
            /// <exception cref="ObjectDisposedException"><paramref name="condition"/> is <see langword="true"/></exception>
            public static void ThrowIf(
                [global::System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute( true )] bool condition,
                object instance
                )
            {
                if(condition)
                {
                    throw new global::System.ObjectDisposedException( instance?.GetType().FullName );
                }
            }
        }

        /// <summary>Poly fill Extensions for <see cref="ObjectDisposedException"/></summary>
        extension( global::System.ArgumentOutOfRangeException )
        {
            /// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is equal to <paramref name="other"/>.</summary>
            /// <param name="value">The argument to validate as not equal to <paramref name="other"/>.</param>
            /// <param name="other">The value to compare with <paramref name="value"/>.</param>
            /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
            public static void ThrowIfEqual<T>( T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute( nameof( value ) )] string? paramName = null )
                where T : IEquatable<T>?
            {
                if(global::System.Collections.Generic.EqualityComparer<T>.Default.Equals( value, other ))
                {
                    ThrowEqual( value, other, paramName );
                }
            }

            /// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is not equal to <paramref name="other"/>.</summary>
            /// <param name="value">The argument to validate as equal to <paramref name="other"/>.</param>
            /// <param name="other">The value to compare with <paramref name="value"/>.</param>
            /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
            public static void ThrowIfNotEqual<T>( T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute( nameof( value ) )] string? paramName = null )
                where T : global::System.IEquatable<T>?
            {
                if(!global::System.Collections.Generic.EqualityComparer<T>.Default.Equals( value, other ))
                {
                    ThrowNotEqual( value, other, paramName );
                }
            }

            /// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is greater than <paramref name="other"/>.</summary>
            /// <param name="value">The argument to validate as less or equal than <paramref name="other"/>.</param>
            /// <param name="other">The value to compare with <paramref name="value"/>.</param>
            /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
            public static void ThrowIfGreaterThan<T>( T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute( nameof( value ) )] string? paramName = null )
                where T : global::System.IComparable<T>
            {
                if(value.CompareTo( other ) > 0)
                {
                    ThrowGreater( value, other, paramName );
                }
            }

            /// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is greater than or equal <paramref name="other"/>.</summary>
            /// <param name="value">The argument to validate as less than <paramref name="other"/>.</param>
            /// <param name="other">The value to compare with <paramref name="value"/>.</param>
            /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
            public static void ThrowIfGreaterThanOrEqual<T>( T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute( nameof( value ) )] string? paramName = null )
                where T : global::System.IComparable<T>
            {
                if(value.CompareTo( other ) >= 0)
                {
                    ThrowGreaterEqual( value, other, paramName );
                }
            }

            /// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is less than <paramref name="other"/>.</summary>
            /// <param name="value">The argument to validate as greatar than or equal than <paramref name="other"/>.</param>
            /// <param name="other">The value to compare with <paramref name="value"/>.</param>
            /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
            public static void ThrowIfLessThan<T>( T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute( nameof( value ) )] string? paramName = null )
                where T : global::System.IComparable<T>
            {
                if(value.CompareTo( other ) < 0)
                {
                    ThrowLess( value, other, paramName );
                }
            }

            /// <summary>Throws an <see cref="ArgumentOutOfRangeException"/> if <paramref name="value"/> is less than or equal <paramref name="other"/>.</summary>
            /// <param name="value">The argument to validate as greatar than than <paramref name="other"/>.</param>
            /// <param name="other">The value to compare with <paramref name="value"/>.</param>
            /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
            public static void ThrowIfLessThanOrEqual<T>( T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpressionAttribute( nameof( value ) )] string? paramName = null )
                where T : global::System.IComparable<T>
            {
                if(value.CompareTo( other ) <= 0)
                {
                    ThrowLessEqual( value, other, paramName );
                }
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowZero<T>( T value, string? paramName )
            {
                string msg = string.Format( global::System.Globalization.CultureInfo.CurrentCulture
                                          , ResourceId.ArgumentOutOfRange_Generic_MustBeNonNegative.GetResourceString()
                                          , paramName
                                          , value
                                          );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg );
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowNegative<T>( T value, string? paramName )
            {
                string msg = string.Format( global::System.Globalization.CultureInfo.CurrentCulture
                                          , ResourceId.ArgumentOutOfRange_Generic_MustBeNonZero.GetResourceString()
                                          , paramName
                                          , value
                                          );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg );
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowNegativeOrZero<T>( T value, string? paramName )
            {
                string msg = string.Format( global::System.Globalization.CultureInfo.CurrentCulture
                                          , ResourceId.ArgumentOutOfRange_Generic_MustBeNonNegativeNonZero.GetResourceString()
                                          , paramName
                                          , value
                                          );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg );
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowGreater<T>( T value, T other, string? paramName )
            {
                var msg = string.Format(
                    global::System.Globalization.CultureInfo.CurrentCulture,
                    ResourceId.ArgumentOutOfRange_Generic_MustBeLessOrEqual.GetResourceString(),
                    paramName,
                    value,
                    other
                    );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg);
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowGreaterEqual<T>( T value, T other, string? paramName )
            {

                var msg = string.Format(
                    global::System.Globalization.CultureInfo.CurrentCulture,
                    ResourceId.ArgumentOutOfRange_Generic_MustBeLess.GetResourceString(),
                    paramName,
                    value,
                    other
                    );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg );
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowLess<T>( T value, T other, string? paramName )
            {
                var msg = string.Format(
                    global::System.Globalization.CultureInfo.CurrentCulture,
                    ResourceId.ArgumentOutOfRange_Generic_MustBeGreaterOrEqual.GetResourceString(),
                    paramName,
                    value,
                    other
                    );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg );
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowLessEqual<T>( T value, T other, string? paramName )
            {
                var msg = string.Format(
                    global::System.Globalization.CultureInfo.CurrentCulture,
                    ResourceId.ArgumentOutOfRange_Generic_MustBeGreater.GetResourceString(),
                    paramName,
                    value,
                    other
                    );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg );
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowEqual<T>( T value, T other, string? paramName )
            {
                var msg = string.Format(
                    global::System.Globalization.CultureInfo.CurrentCulture,
                    ResourceId.ArgumentOutOfRange_Generic_MustBeNotEqual.GetResourceString(),
                    paramName,
                    value,
                    other
                    );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg);
            }

            [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
            private static void ThrowNotEqual<T>( T value, T other, string? paramName )
            {
                var msg = string.Format(
                    global::System.Globalization.CultureInfo.CurrentCulture,
                    ResourceId.ArgumentOutOfRange_Generic_MustBeEqual.GetResourceString(),
                    paramName,
                    value,
                    other
                    );

                throw new global::System.ArgumentOutOfRangeException( paramName, value, msg );
            }
        }
    }
}
