// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// Licensed under the Apache-2.0 WITH LLVM-exception license. See the LICENSE.md file in the project root for full license information.

namespace Ubiquity.NET.SrcGeneration.CSharp
{
    /// <summary>Extensions to <see cref="IndentedTextWriter"/> to support C# source generation</summary>
    [SuppressMessage( "Performance", "CA1822:Mark members as static", Justification = "extension" )]
    [SuppressMessage( "Design", "CA1034:Nested types should not be visible", Justification = "extension" )]
    public static class IndentedTextWriterCsExtensions
    {
        /// <summary>Writes a standard <c>auto-generated</c> comment block</summary>
        /// <param name="self">Writer to apply extension method to</param>
        /// <param name="toolName">Name of the generating tool (included in comment)</param>
        /// <param name="toolVersion">Version of the tool (included in comment)</param>
        /// <param name="source">Source of the generated file [Default: null]</param>
        public static void WriteAutoGeneratedComment( this IndentedTextWriter self, string toolName, string toolVersion, string? source = null )
        {
            ArgumentNullException.ThrowIfNull( self );

            using var scope = self.WriteAutoGeneratedCommentBlock(toolName, toolVersion);

            if(!string.IsNullOrWhiteSpace( source ))
            {
                self.WriteLine( $"//    From: {source}" );
            }
            else
            {
                self.WriteLine( "//" );
            }
        }

        /// <summary>Writes a standard <c>auto-generated</c> comment block returning the scope for additional contents</summary>
        /// <param name="self">Writer to apply extension method to</param>
        /// <param name="toolName">Name of the generating tool (included in comment)</param>
        /// <param name="toolVersion">Version of the tool (included in comment)</param>
        /// <returns>Disposable scope for the namespace (closes the scope on dispose)</returns>
        /// <remarks>
        /// To remain syntactically valid all lines written to the writer within this block
        /// <em><b>MUST</b></em> include a leading "//" (this does NOT alter the prefix requirement
        /// for the writer).
        /// </remarks>
        public static IDisposable WriteAutoGeneratedCommentBlock( this IndentedTextWriter self, string toolName, string toolVersion )
        {
            ArgumentNullException.ThrowIfNull( self );

            string open = $"""
            // ------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //     {toolName} [{toolVersion}]
            """;

            string close = """
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            // ------------------------------------------------------------------------------
            """;
            return self.Block( open, close, indented: false );
        }

        /// <summary>Writes a Namespace declaration scope</summary>
        /// <param name="self">Writer to apply extension method to</param>
        /// <param name="namespaceName">Name of the namespace</param>
        /// <returns>Disposable scope for the namespace (closes the scope on dispose)</returns>
        public static IDisposable Namespace( this IndentedTextWriter self, string namespaceName )
        {
            return self.Scope( $"namespace {namespaceName}" );
        }

        /// <summary>Writes a C# struct declaration</summary>
        /// <param name="self">Writer to apply extension method to</param>
        /// <param name="access">Access (prefix) for the struct declaration</param>
        /// <param name="structName">name of the structure</param>
        /// <returns>Disposable scope that closes the struct declaration on <see cref="IDisposable.Dispose"/></returns>
        public static IDisposable Struct( this IndentedTextWriter self, string access, string structName )
        {
            return self.Scope( $"{access} struct {structName}" );
        }

        /// <summary>Write an "unsafe" region as a scope</summary>
        /// <param name="self">Writer to apply extension method to</param>
        /// <returns>Disposable scope that closes the region declaration on <see cref="IDisposable.Dispose"/></returns>
        public static IDisposable UnsafeScope( this IndentedTextWriter self )
        {
            return self.Scope( "unsafe" );
        }

        /// <summary>Write a scope as a region</summary>
        /// <param name="self">Writer to apply extension method to</param>
        /// <param name="leadingLine">Leading line of the scope, if any.</param>
        /// <returns>Disposable scope that closes the struct declaration on <see cref="IDisposable.Dispose"/></returns>
        /// <remarks>
        /// <paramref name="leadingLine"/> is written on a line of it's own then <see cref="CSharpLanguage.ScopeOpen"/>
        /// is written and the indentation is pushed and the returned disposer will outdent and write
        /// <see cref="CSharpLanguage.ScopeClose"/>. Thus any values written until the return is disposed is indented
        /// automatically.
        /// </remarks>
        public static IDisposable Scope( this IndentedTextWriter self, string? leadingLine = null )
        {
            return self.Block( CSharpLanguage.ScopeOpen, CSharpLanguage.ScopeClose, leadingLine );
        }

        /// <summary>Writes <paramref name="txt"/> as a multi-line comment</summary>
        /// <param name="self">Writer to apply extension method to</param>
        /// <param name="txt">Text of the comment</param>
        public static void MultiLineComment( this IndentedTextWriter self, string? txt )
        {
            ArgumentNullException.ThrowIfNull( self );
            if(txt is null)
            {
                return;
            }

            string[] lines = [ .. txt.GetCommentLines() ];
            if(lines.Length > 0)
            {
                using(self.Block( "/*", "*/" ))
                {
                    foreach(string line in lines)
                    {
                        self.WriteLine( line );
                    }
                }
            }
        }

        /// <summary>Writes a C# class scope</summary>
        /// <param name="self">Writer to apply extension method to</param>
        /// <param name="access">access modifier (prefix) for the declaration</param>
        /// <param name="className">Name of the class to generate</param>
        /// <returns>Disposable scope that closes the class declaration on <see cref="IDisposable.Dispose"/></returns>
        public static IDisposable Class( this IndentedTextWriter self, string access, string className )
        {
            ArgumentNullException.ThrowIfNull( self );

            self.WriteLine( $"{access} class {className}" );
            return self.Scope();
        }
    }
}
