// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// Licensed under the Apache-2.0 WITH LLVM-exception license. See the LICENSE.md file in the project root for full license information.

using Ubiquity.NET.Runtime.Utils;

namespace Kaleidoscope.Grammar.AST
{
    /// <summary>Interface for a variable declaration</summary>
    /// <remarks>
    /// There are multiple forms of variable declarations (local, parameter, etc...).
    /// This interface provides the common implementation for any such variables.
    /// </remarks>
    public interface IVariableDeclaration
        : IAstNode
    {
        /// <summary>Gets the name of the variable</summary>
        string Name { get; }

        /// <summary>Gets a value indicating whether this variable is generated by the compiler/language</summary>
        bool CompilerGenerated { get; }
    }
}
