// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// Licensed under the Apache-2.0 WITH LLVM-exception license. See the LICENSE.md file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Text;

using Ubiquity.NET.Extensions;
using Ubiquity.NET.Runtime.Utils;

namespace Kaleidoscope.Grammar.AST
{
    /// <summary>Local variable declaration AST node</summary>
    public sealed class LocalVariableDeclaration
        : AstNode
        , IVariableDeclaration
    {
        /// <summary>Initializes a new instance of the <see cref="LocalVariableDeclaration"/> class.</summary>
        /// <param name="location">Location of the node in the input source</param>
        /// <param name="name">Name of the variable</param>
        /// <param name="initializer">initializer for the expression</param>
        /// <param name="compilerGenerated">flag to indicate if this variable is generated by the parsing of the language</param>
        public LocalVariableDeclaration( SourceRange location, string name, IExpression? initializer, bool compilerGenerated = false )
            : base( location )
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(name);

            Name = name;
            Initializer = initializer;
            CompilerGenerated = compilerGenerated;
        }

        /// <inheritdoc/>
        public string Name { get; }

        /// <summary>Gets the initializer for this declaration (if any)</summary>
        public IExpression? Initializer { get; }

        /// <inheritdoc/>
        public bool CompilerGenerated { get; }

        /// <inheritdoc cref="BinaryOperatorExpression.Accept{TResult, TArg}(IAstVisitor{TResult, TArg}, ref readonly TArg)"/>
        public override TResult? Accept<TResult>( IAstVisitor<TResult> visitor )
            where TResult : default
        {
            return visitor is IKaleidoscopeAstVisitor<TResult> klsVisitor
                   ? klsVisitor.Visit( this )
                   : visitor.Visit( this );
        }

        /// <inheritdoc cref="BinaryOperatorExpression.Accept{TResult, TArg}(IAstVisitor{TResult, TArg}, ref readonly TArg)"/>
        public override TResult? Accept<TResult, TArg>( IAstVisitor<TResult, TArg> visitor, ref readonly TArg arg )
            where TResult : default
        {
            return visitor is IKaleidoscopeAstVisitor<TResult, TArg> klsVisitor
                   ? klsVisitor.Visit( this, in arg )
                   : visitor.Visit( this, in arg );
        }

        /// <inheritdoc/>
        public override IEnumerable<IAstNode> Children
        {
            get
            {
                if(Initializer != null)
                {
                    yield return Initializer;
                }
            }
        }

        /// <inheritdoc/>
        public override string ToString( )
        {
            var bldr = new StringBuilder();
            if(CompilerGenerated)
            {
                bldr.Append( "[CompilerGenerated]" );
            }

            bldr.Append( "Declare(" );
            bldr.Append( Name );
            if(Initializer != null)
            {
                bldr.Append( ", " );
                bldr.Append( Initializer );
            }

            bldr.Append( ')' );
            return bldr.ToString();
        }
    }
}
