// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// Licensed under the Apache-2.0 WITH LLVM-exception license. See the LICENSE.md file in the project root for full license information.

using Ubiquity.NET.SrcGeneration.CSharp;

// simplification for self==null test cases
using CsExtensions = Ubiquity.NET.SrcGeneration.CSharp.IndentedTextWriterExtensions;

namespace Ubiquity.NET.SrcGeneration.UT.CSharp
{
    [TestClass]
    [ExcludeFromCodeCoverage]
    public class IndentedTestWriterExtensionTests
    {
        #region Basic API Validation
#pragma warning disable CS8625 // Cannot convert null literal to non-nullable reference type.
        [TestMethod]
        public void Methods_report_exception_with_invalid_input( )
        {
            var ex = Assert.ThrowsExactly<ArgumentNullException>(()=>CsExtensions.WriteAutoGeneratedComment(null, "tool", "version"));
            Assert.AreEqual( "self", ex.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = CsExtensions.WriteAutoGeneratedCommentBlock(null, "tool", "version");
            } );
            Assert.AreEqual( "self", ex.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = CsExtensions.Namespace(null, "My.Namespace");
            } );
            Assert.AreEqual( "self", ex.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = CsExtensions.Struct(null, "access", "StructName");
            } );
            Assert.AreEqual( "self", ex.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = CsExtensions.UnsafeScope(null);
            } );
            Assert.AreEqual( "self", ex.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = CsExtensions.Scope(null);
            } );
            Assert.AreEqual( "self", ex.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) => CsExtensions.MultiLineComment( null, null ) );
            Assert.AreEqual( "self", ex.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = CsExtensions.Class(null, "access", "ClassName");
            } );
            Assert.AreEqual( "self", ex.ParamName );

            // additional param checks (not "self")
            using var writer = new OwningIndentedStringWriter();
            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) => writer.WriteAutoGeneratedComment( null, "version" ) );
            Assert.AreEqual( "toolName", ex.ParamName );

            var argEx = Assert.ThrowsExactly<ArgumentException>( ( ) => writer.WriteAutoGeneratedComment( string.Empty, "version" ) );
            Assert.AreEqual( "toolName", argEx.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) => writer.WriteAutoGeneratedComment( " \t ", "version" ) );
            Assert.AreEqual( "toolName", argEx.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) => writer.WriteAutoGeneratedComment( "tool", null ) );
            Assert.AreEqual( "toolVersion", ex.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) => writer.WriteAutoGeneratedComment( "tool", string.Empty ) );
            Assert.AreEqual( "toolVersion", argEx.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) => writer.WriteAutoGeneratedComment( "tool", " \t " ) );
            Assert.AreEqual( "toolVersion", argEx.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = writer.WriteAutoGeneratedCommentBlock( null, "version");
            } );
            Assert.AreEqual( "toolName", ex.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.WriteAutoGeneratedCommentBlock( string.Empty, "version");
            } );
            Assert.AreEqual( "toolName", argEx.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.WriteAutoGeneratedCommentBlock( " \t ", "version");
            } );
            Assert.AreEqual( "toolName", argEx.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = writer.WriteAutoGeneratedCommentBlock( "tool", null);
            } );
            Assert.AreEqual( "toolVersion", ex.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.WriteAutoGeneratedCommentBlock( "tool", string.Empty);
            } );
            Assert.AreEqual( "toolVersion", argEx.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.WriteAutoGeneratedCommentBlock( "tool", " \t ");
            } );
            Assert.AreEqual( "toolVersion", argEx.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = writer.Namespace( null);
            } );
            Assert.AreEqual( "namespaceName", ex.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.Namespace( string.Empty);
            } );
            Assert.AreEqual( "namespaceName", argEx.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.Namespace( " \t ");
            } );
            Assert.AreEqual( "namespaceName", argEx.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = writer.Struct( null, null);
            } );
            Assert.AreEqual( "structName", ex.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.Struct( null, string.Empty);
            } );
            Assert.AreEqual( "structName", argEx.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.Struct( null, " \t ");
            } );
            Assert.AreEqual( "structName", argEx.ParamName );

            ex = Assert.ThrowsExactly<ArgumentNullException>( ( ) =>
            {
                using var scope = writer.Class( null, null);
            } );
            Assert.AreEqual( "className", ex.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.Class(null, string.Empty);
            } );
            Assert.AreEqual( "className", argEx.ParamName );

            argEx = Assert.ThrowsExactly<ArgumentException>( ( ) =>
            {
                using var scope = writer.Class( null, " \t ");
            } );
            Assert.AreEqual( "className", argEx.ParamName );
        }
#pragma warning restore CS8625 // Cannot convert null literal to non-nullable reference type.
        #endregion

        [TestMethod]
        public void WriteAutoGeneratedComment_succeeds( )
        {
           const string expected = """
            // ------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //     MyTool [1.2.3.4]
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            // ------------------------------------------------------------------------------
            """;

            using var writer = new OwningIndentedStringWriter();
            writer.WriteAutoGeneratedComment("MyTool", "1.2.3.4");
            Assert.AreEqual(expected, writer.ToString());
        }

        [TestMethod]
        public void WriteAutoGeneratedComment_with_source_succeeds( )
        {
            const string expected = """
            // ------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //     MyTool [1.2.3.4]
            //     From: C:\SomeDir\MyFile.cs
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            // ------------------------------------------------------------------------------
            """;

            using var writer = new OwningIndentedStringWriter();
            writer.WriteAutoGeneratedComment( "MyTool", "1.2.3.4", @"C:\SomeDir\MyFile.cs" );
            Assert.AreEqual( expected, writer.ToString() );
        }

        [TestMethod]
        public void WriteAutoGeneratedCommentBlock_succeeds( )
        {
            const string expected = """
            // ------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //     MyTool [1.2.3.4]
            //
            //     This is a test
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            // ------------------------------------------------------------------------------
            """;

            using var writer = new OwningIndentedStringWriter();
            using(writer.WriteAutoGeneratedCommentBlock( "MyTool", "1.2.3.4" ))
            {
                writer.WriteLine("//");
                writer.WriteLine("//     This is a test");
                writer.WriteLine("//");
            }

            Assert.AreEqual(expected, writer.ToString());
        }

        [TestMethod]
        public void Namespace_succeeds( )
        {
            const string expected = """
            namespace My.Namespace
            {
                // This is a test...
            }
            """;

            using var writer = new OwningIndentedStringWriter();
            using(writer.Namespace( "My.Namespace" ))
            {
                writer.WriteLine( "// This is a test..." );
            }

            Assert.AreEqual( expected, writer.ToString() );
        }

        [TestMethod]
        public void Struct_succeeds( )
        {
            const string expected = """
            public partial struct MyStruct
            {
                // This is a test...
            }
            """;

            using var writer = new OwningIndentedStringWriter();
            using(writer.Struct("public partial", "MyStruct" ))
            {
                writer.WriteLine( "// This is a test..." );
            }

            Assert.AreEqual( expected, writer.ToString() );
        }

        [TestMethod]
        public void UnsafeScope_succeeds( )
        {
            const string expected = """
            unsafe
            {
                // This is a test...
            }
            """;

            using var writer = new OwningIndentedStringWriter();
            using(writer.UnsafeScope())
            {
                writer.WriteLine( "// This is a test..." );
            }

            Assert.AreEqual( expected, writer.ToString() );
        }

        [TestMethod]
        public void Scope_with_leading_succeeds( )
        {
            const string expected = """
            // C# scope
            {
                // This is a test...
            }
            """;

            using var writer = new OwningIndentedStringWriter();
            using(writer.Scope( "// C# scope" ))
            {
                writer.WriteLine( "// This is a test..." );
            }

            Assert.AreEqual( expected, writer.ToString() );
        }

        [TestMethod]
        public void Scope_without_leading_succeeds( )
        {
            const string expected = """
            {
                // This is a test...
            }
            """;

            using var writer = new OwningIndentedStringWriter();
            using(writer.Scope( ))
            {
                writer.WriteLine( "// This is a test..." );
            }

            Assert.AreEqual( expected, writer.ToString() );
        }

        [TestMethod]
        public void MultiLineComment_with_null_or_empty_text_is_nop( )
        {
            using var writer = new OwningIndentedStringWriter();
            writer.MultiLineComment(null);
            Assert.AreEqual(0, ((StringWriter)writer.InnerWriter).GetStringBuilder().Length);

            writer.MultiLineComment( string.Empty );
            Assert.AreEqual( 0, ((StringWriter)writer.InnerWriter).GetStringBuilder().Length );

            writer.MultiLineComment( " \t " );
            Assert.AreEqual( 0, ((StringWriter)writer.InnerWriter).GetStringBuilder().Length );
        }

        [TestMethod]
        public void MultiLineComment_succeeds( )
        {
            const string expected = """
            /*
                This is a test...
                of a multi-line comment
            */
            """;

            using var writer = new OwningIndentedStringWriter();
            writer.MultiLineComment( string.Join(Environment.NewLine, ["This is a test...", "of a multi-line comment"] ));

            Assert.AreEqual( expected, writer.ToString() );
        }

        [TestMethod]
        public void Class_succeeds( )
        {
            const string expected = """
            public partial class MyClass
            {
                // This is a test...
            }
            """;

            using var writer = new OwningIndentedStringWriter();
            using(writer.Class( "public partial", "MyClass" ))
            {
                writer.WriteLine( "// This is a test..." );
            }

            Assert.AreEqual( expected, writer.ToString() );
        }
    }
}
