// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Llvm.NET.Interop
{
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public struct LLVMBasicBlockRef
        : IEquatable<LLVMBasicBlockRef>
    {
        public override int GetHashCode( ) => Handle.GetHashCode( );

        public override bool Equals( object obj )
            => !( obj is null )
             && ( obj is LLVMBasicBlockRef r )
             && ( r.Handle == Handle );

        public bool Equals( LLVMBasicBlockRef other ) => Handle == other.Handle;

        public static bool operator ==( LLVMBasicBlockRef lhs, LLVMBasicBlockRef rhs )
            => EqualityComparer<LLVMBasicBlockRef>.Default.Equals( lhs, rhs );

        public static bool operator !=( LLVMBasicBlockRef lhs, LLVMBasicBlockRef rhs ) => !( lhs == rhs );

        public static LLVMBasicBlockRef Zero { get; } = new LLVMBasicBlockRef(IntPtr.Zero);

        internal LLVMBasicBlockRef( IntPtr p )
        {
            Handle = p;
        }

        private readonly IntPtr Handle;
    }
}
