// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Llvm.NET.Interop
{
    [SecurityCritical]
    [GeneratedCode( "LlvmBindingsGenerator", "2.17941.31104.49410" )]
    public class LLVMErrorRef
        : LlvmObjectRef
    {
        public LLVMErrorRef( IntPtr handle, bool owner )
            : base( owner )
        {
            SetHandle( handle );
            LazyMessage = new Lazy<string>( InternalGetMessage );
        }

        public override string ToString()
        {
            return LazyMessage.Value;
        }

        [SecurityCritical]
        protected override bool ReleaseHandle( )
        {
            LLVMConsumeError( handle );
            return true;
        }

        private LLVMErrorRef( )
            : base( true )
        {
        }

        private string InternalGetMessage( )
        {
            if( IsInvalid )
            {
                return string.Empty;
            }

            string retVal = LLVMGetErrorMessage( handle );
            SetHandle( IntPtr.Zero );
            SetHandleAsInvalid( );
            return retVal;
        }

        // use Lazy to cache result of the underlying destructive get
        Lazy<string> LazyMessage;

        [DllImport( NativeMethods.LibraryPath, CallingConvention = CallingConvention.Cdecl )]
        private static extern void LLVMConsumeError( IntPtr p );

        [DllImport( NativeMethods.LibraryPath, CallingConvention = CallingConvention.Cdecl )]
        [return: MarshalAs( UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof( ErrorMessageMarshaler ) )]
        private static extern string LLVMGetErrorMessage( IntPtr p );
    }
}
