// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Llvm.NET.Interop
{
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public struct LLVMModuleRef
        : IEquatable<LLVMModuleRef>
    {
        public override int GetHashCode( ) => Handle.GetHashCode( );

        public override bool Equals( object obj )
            => !( obj is null )
             && ( obj is LLVMModuleRef r )
             && ( r.Handle == Handle );

        public bool Equals( LLVMModuleRef other ) => Handle == other.Handle;

        public static bool operator ==( LLVMModuleRef lhs, LLVMModuleRef rhs )
            => EqualityComparer<LLVMModuleRef>.Default.Equals( lhs, rhs );

        public static bool operator !=( LLVMModuleRef lhs, LLVMModuleRef rhs ) => !( lhs == rhs );

        public static LLVMModuleRef Zero { get; } = new LLVMModuleRef(IntPtr.Zero);

        public IntPtr ToIntPtr() => Handle;

        public static implicit operator IntPtr(LLVMModuleRef value) => value.ToIntPtr();

        internal LLVMModuleRef( IntPtr p )
        {
            Handle = p;
        }

        private readonly IntPtr Handle;
    }
}
