// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Llvm.NET.Interop
{
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public struct LLVMNamedMDNodeRef
        : IEquatable<LLVMNamedMDNodeRef>
    {
        public override int GetHashCode( ) => Handle.GetHashCode( );

        public override bool Equals( object obj )
            => !( obj is null )
             && ( obj is LLVMNamedMDNodeRef r )
             && ( r.Handle == Handle );

        public bool Equals( LLVMNamedMDNodeRef other ) => Handle == other.Handle;

        public static bool operator ==( LLVMNamedMDNodeRef lhs, LLVMNamedMDNodeRef rhs )
            => EqualityComparer<LLVMNamedMDNodeRef>.Default.Equals( lhs, rhs );

        public static bool operator !=( LLVMNamedMDNodeRef lhs, LLVMNamedMDNodeRef rhs ) => !( lhs == rhs );

        internal LLVMNamedMDNodeRef( IntPtr p )
        {
            Handle = p;
        }

        private readonly IntPtr Handle;
    }
}
