// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Llvm.NET.Interop
{
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public struct LLVMUseRef
        : IEquatable<LLVMUseRef>
    {
        public override int GetHashCode( ) => Handle.GetHashCode( );

        public override bool Equals( object obj )
            => !( obj is null )
             && ( obj is LLVMUseRef r )
             && ( r.Handle == Handle );

        public bool Equals( LLVMUseRef other ) => Handle == other.Handle;

        public static bool operator ==( LLVMUseRef lhs, LLVMUseRef rhs )
            => EqualityComparer<LLVMUseRef>.Default.Equals( lhs, rhs );

        public static bool operator !=( LLVMUseRef lhs, LLVMUseRef rhs ) => !( lhs == rhs );

        public static LLVMUseRef Zero { get; } = new LLVMUseRef(IntPtr.Zero);

        public IntPtr ToIntPtr() => Handle;

        public static implicit operator IntPtr(LLVMUseRef value) => value.ToIntPtr();

        internal LLVMUseRef( IntPtr p )
        {
            Handle = p;
        }

        private readonly IntPtr Handle;
    }
}
