// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Llvm.NET.Interop
{
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public struct LLVMJITEventListenerRef
        : IEquatable<LLVMJITEventListenerRef>
    {
        public override int GetHashCode( ) => Handle.GetHashCode( );

        public override bool Equals( object obj )
            => !( obj is null )
             && ( obj is LLVMJITEventListenerRef r )
             && ( r.Handle == Handle );

        public bool Equals( LLVMJITEventListenerRef other ) => Handle == other.Handle;

        public static bool operator ==( LLVMJITEventListenerRef lhs, LLVMJITEventListenerRef rhs )
            => EqualityComparer<LLVMJITEventListenerRef>.Default.Equals( lhs, rhs );

        public static bool operator !=( LLVMJITEventListenerRef lhs, LLVMJITEventListenerRef rhs ) => !( lhs == rhs );

        public static LLVMJITEventListenerRef Zero { get; } = new LLVMJITEventListenerRef(IntPtr.Zero);

        public IntPtr ToIntPtr() => Handle;

        public static implicit operator IntPtr(LLVMJITEventListenerRef value) => value.ToIntPtr();

        internal LLVMJITEventListenerRef( IntPtr p )
        {
            Handle = p;
        }

        private readonly IntPtr Handle;
    }
}
