// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Llvm.NET.Interop
{
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public struct LLVMMetadataRef
        : IEquatable<LLVMMetadataRef>
    {
        public override int GetHashCode( ) => Handle.GetHashCode( );

        public override bool Equals( object obj )
            => !( obj is null )
             && ( obj is LLVMMetadataRef r )
             && ( r.Handle == Handle );

        public bool Equals( LLVMMetadataRef other ) => Handle == other.Handle;

        public static bool operator ==( LLVMMetadataRef lhs, LLVMMetadataRef rhs )
            => EqualityComparer<LLVMMetadataRef>.Default.Equals( lhs, rhs );

        public static bool operator !=( LLVMMetadataRef lhs, LLVMMetadataRef rhs ) => !( lhs == rhs );

        public static LLVMMetadataRef Zero { get; } = new LLVMMetadataRef(IntPtr.Zero);

        internal LLVMMetadataRef( IntPtr p )
        {
            Handle = p;
        }

        private readonly IntPtr Handle;
    }
}
