// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Llvm.NET.Interop
{
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public struct LLVMAttributeRef
        : IEquatable<LLVMAttributeRef>
    {
        public override int GetHashCode( ) => Handle.GetHashCode( );

        public override bool Equals( object obj )
            => !( obj is null )
             && ( obj is LLVMAttributeRef r )
             && ( r.Handle == Handle );

        public bool Equals( LLVMAttributeRef other ) => Handle == other.Handle;

        public static bool operator ==( LLVMAttributeRef lhs, LLVMAttributeRef rhs )
            => EqualityComparer<LLVMAttributeRef>.Default.Equals( lhs, rhs );

        public static bool operator !=( LLVMAttributeRef lhs, LLVMAttributeRef rhs ) => !( lhs == rhs );

        public static LLVMAttributeRef Zero { get; } = new LLVMAttributeRef(IntPtr.Zero);

        public IntPtr ToIntPtr() => Handle;

        public static implicit operator IntPtr(LLVMAttributeRef value) => value.ToIntPtr();

        internal LLVMAttributeRef( IntPtr p )
        {
            Handle = p;
        }

        private readonly IntPtr Handle;
    }
}
