// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Llvm.NET.Interop
{
    [SecurityCritical]
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public class lto_module_t
        : LlvmObjectRef
    {
        public lto_module_t( IntPtr handle, bool owner )
            : base( owner )
        {
            SetHandle( handle );
        }

        public static lto_module_t Zero { get; } = new lto_module_t(IntPtr.Zero, false);

        [SecurityCritical]
        protected override bool ReleaseHandle( )
        {
            lto_module_dispose( handle );
            return true;
        }

        private lto_module_t( )
            : base( true )
        {
        }

        [DllImport( NativeMethods.LibraryPath, CallingConvention = CallingConvention.Cdecl )]
        private static extern void lto_module_dispose( IntPtr p );
    }

    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    internal class lto_module_tAlias
        : lto_module_t
    {
        private lto_module_tAlias()
            : base( IntPtr.Zero, false )
        {
        }
    }
}
