// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Llvm.NET.Interop
{
    public static partial class NativeMethods
    {
        /** Writes a module to the specified path. Returns 0 on success. */
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMStatus LLVMWriteBitcodeToFile( LLVMModuleRef M, [MarshalAs( UnmanagedType.LPStr )]string Path );

        /** Writes a module to an open file descriptor. Returns 0 on success. */
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMStatus LLVMWriteBitcodeToFD( LLVMModuleRef M, int FD, int ShouldClose, int Unbuffered );

        /** Writes a module to a new memory buffer and returns it. */
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMMemoryBufferRef LLVMWriteBitcodeToMemoryBuffer( LLVMModuleRef M );

    }
}
