// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Llvm.NET.Interop
{
    /// <include file="Comdat.xml" path='LibLLVMAPI/Enumeration[@name="LLVMComdatSelectionKind"]/*[not(self::Item)]' />
    [GeneratedCode("LlvmBindingsGenerator","2.17941.31104.49410")]
    public enum LLVMComdatSelectionKind : global::System.Int32
    {
        /// <include file="Comdat.xml" path='LibLLVMAPI/Enumeration[@name="LLVMComdatSelectionKind"]/Item[@name="LLVMAnyComdatSelectionKind"]/*' />
        LLVMAnyComdatSelectionKind = 0,
        /// <include file="Comdat.xml" path='LibLLVMAPI/Enumeration[@name="LLVMComdatSelectionKind"]/Item[@name="LLVMExactMatchComdatSelectionKind"]/*' />
        LLVMExactMatchComdatSelectionKind = 1,
        /// <include file="Comdat.xml" path='LibLLVMAPI/Enumeration[@name="LLVMComdatSelectionKind"]/Item[@name="LLVMLargestComdatSelectionKind"]/*' />
        LLVMLargestComdatSelectionKind = 2,
        /// <include file="Comdat.xml" path='LibLLVMAPI/Enumeration[@name="LLVMComdatSelectionKind"]/Item[@name="LLVMNoDuplicatesComdatSelectionKind"]/*' />
        LLVMNoDuplicatesComdatSelectionKind = 3,
        /// <include file="Comdat.xml" path='LibLLVMAPI/Enumeration[@name="LLVMComdatSelectionKind"]/Item[@name="LLVMSameSizeComdatSelectionKind"]/*' />
        LLVMSameSizeComdatSelectionKind = 4,
    }

    public static partial class NativeMethods
    {
        /// <include file="Comdat.xml" path='LibLLVMAPI/Function[@name="LLVMGetOrInsertComdat"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMComdatRef LLVMGetOrInsertComdat( LLVMModuleRef M, [MarshalAs( UnmanagedType.LPStr )]string Name );

        /// <include file="Comdat.xml" path='LibLLVMAPI/Function[@name="LLVMGetComdat"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMComdatRef LLVMGetComdat( LLVMValueRef V );

        /// <include file="Comdat.xml" path='LibLLVMAPI/Function[@name="LLVMSetComdat"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMSetComdat( LLVMValueRef V, LLVMComdatRef C );

        /// <include file="Comdat.xml" path='LibLLVMAPI/Function[@name="LLVMGetComdatSelectionKind"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMComdatSelectionKind LLVMGetComdatSelectionKind( LLVMComdatRef C );

        /// <include file="Comdat.xml" path='LibLLVMAPI/Function[@name="LLVMSetComdatSelectionKind"]/*' />
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern void LLVMSetComdatSelectionKind( LLVMComdatRef C, LLVMComdatSelectionKind Kind );

    }
}
