// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 2.17941.31104.49410
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.InteropServices;
using System.Security;

namespace Llvm.NET.Interop
{
    public static partial class NativeMethods
    {
        /**
         * Returns the type id for the given error instance, which must be a failure
         * value (i.e. non-null).
         */
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMErrorTypeId LLVMGetErrorTypeId( LLVMErrorRef Err );

        /**
         * Returns the given string's error message. This operation consumes the error,
         * and the given LLVMErrorRef value is not usable once this call returns.
         * The caller is responsible for disposing of the string by calling
         * LLVMDisposeErrorMessage.
         */
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        unsafe public static extern sbyte* LLVMGetErrorMessage( LLVMErrorRef Err );

        /**
         * Returns the type id for llvm StringError.
         */
        [SuppressUnmanagedCodeSecurity]
        [DllImport( LibraryPath, CallingConvention=global::System.Runtime.InteropServices.CallingConvention.Cdecl )]
        public static extern LLVMErrorTypeId LLVMGetStringErrorTypeId(  );

    }
}
