// Copyright (c) Ubiquity.NET Contributors. All rights reserved.
// Licensed under the Apache-2.0 WITH LLVM-exception license. See the LICENSE.md file in the project root for full license information.

namespace Ubiquity.NET.Extensions.Properties
{
    // RESX file generator does not use `partial` and VS2022 doesn't correctly support
    // C# 14 `extension` so derivation is the only option at present...
    // CONSIDER: Generator to create this from an attribute that includes the type of the Resources
    //           generator/Analyzer should validate that the type has a ResourceManager member.
    //           (Effectively a C++ concept since the type is generated by a SingleFileGenerator
    //           it doesn't have an interface or base type to use as a constraint)
    internal static class SR
    {
        internal static string Format<TArg0>( [NotNull] string resourceName, TArg0 arg0 )
        {
            ArgumentNullException.ThrowIfNull(resourceName);

            string? fmt = Resources.ResourceManager.GetString(resourceName, Resources.Culture) ?? throw new ResourceNotFoundException(resourceName);
            return string.Format(Resources.Culture, fmt, arg0);
        }

        internal static string Format<TArg0, TArg1>( [NotNull] string resourceName, TArg0 arg0, TArg1 arg1 )
        {
            ArgumentNullException.ThrowIfNull(resourceName);

            string? fmt = Resources.ResourceManager.GetString(resourceName, Resources.Culture) ?? throw new ResourceNotFoundException(resourceName);
            return string.Format(Resources.Culture, fmt, arg0, arg1);
        }

        internal static string Format<TArg0, TArg1, TArg2>( [NotNull] string resourceName, TArg0 arg0, TArg1 arg1, TArg2 arg2 )
        {
            ArgumentNullException.ThrowIfNull(resourceName);

            string? fmt = Resources.ResourceManager.GetString(resourceName, Resources.Culture) ?? throw new ResourceNotFoundException(resourceName);
            return string.Format(Resources.Culture, fmt, arg0, arg1, arg2);
        }

        internal static string Format( [NotNull] string resourceName, params IEnumerable<object?> args )
        {
            ArgumentNullException.ThrowIfNull(resourceName);

            string? fmt = Resources.ResourceManager.GetString(resourceName, Resources.Culture) ?? throw new ResourceNotFoundException(resourceName);
            return string.Format(Resources.Culture, fmt, args);
        }
    }
}
